"""Helper to resolve how the acting user is named in export metadata.

The JWT issued by this application carries only ``permissions`` as additional
claims (see app/application/usecases/login.py) — no ``email`` claim. We must
therefore always fall back to a user-repository lookup. This helper centralises
that logic so every route shares a single implementation.
"""

from __future__ import annotations

from uuid import UUID

from flask_jwt_extended import get_jwt_identity

from app.application.usecases.otp_login import is_placeholder_email


def get_requester_label(user_repository) -> str:  # type: ignore[no-untyped-def]
    """Return how export files name the authenticated user ("Generated by …").

    Display name, else real e-mail, else phone. A phone-only account's e-mail is a
    synthetic ``phone-…@no-email…`` address, an identifier that is never shown.
    Returns ``"unknown"`` if the identity is missing or the user row cannot be
    found — this should not happen in practice under normal auth flow.

    Args:
        user_repository: Any repository implementing ``find_by_id(UUID)``.
    """
    try:
        raw_id = get_jwt_identity()
        if not raw_id:
            return "unknown"
        user = user_repository.find_by_id(UUID(raw_id))
        if user is None:
            return "unknown"
        display_name = (user.display_name or "").strip()
        email = None if is_placeholder_email(user.email) else user.email
        return display_name or email or user.phone or "unknown"
    except Exception:
        return "unknown"
