"""Unit tests for the narrow auto-generated released_funds payment-method-only
carve-out in UpdateInvoiceUseCase.

Baseline: any auto-generated invoice rejects ALL edits (AutoGeneratedInvoiceError).
The carve-out lifts that rejection ONLY when the invoice is an auto-generated
released_funds release AND the request's ONLY populated field is
payment_method_id (set to a UUID or explicitly cleared to None) — every other
updatable field must be absent/unset. Any other field present disqualifies the
carve-out and the baseline rejection applies.
"""

from __future__ import annotations

from datetime import date, datetime, timezone
from decimal import Decimal
from unittest.mock import MagicMock
from uuid import uuid4

import pytest

from app.application.invoice.ports import IInvoiceRepository
from app.application.invoice.update_invoice import UpdateInvoiceUseCase, UpdateInvoiceRequest
from app.application.payment_methods.ports import IPaymentMethodRepository
from app.domain.companies.exceptions import ForbiddenCompanyError
from app.domain.entities.invoice import Invoice, InvoiceType
from app.domain.exceptions.invoice_exceptions import AutoGeneratedInvoiceError
from app.domain.payment_methods.exceptions import PaymentMethodNotActiveError, PaymentMethodNotFoundError
from app.domain.payment_methods.payment_method import PaymentMethod
from app.domain.value_objects.invoice_item import InvoiceItem


def _make_release_invoice(project_id=None, *, is_auto_generated=True, type_=InvoiceType.RELEASED_FUNDS, **overrides):
    now = datetime.now(timezone.utc)
    defaults = dict(
        id=uuid4(),
        project_id=project_id or uuid4(),
        invoice_number="FR-2026-0001",
        type=type_,
        issue_date=date.today(),
        recipient_name="ACME Corp",
        items=[InvoiceItem(description="Release", quantity=Decimal("1"), unit_price=Decimal("100"))],
        created_by=uuid4(),
        created_at=now,
        updated_at=now,
        is_auto_generated=is_auto_generated,
    )
    defaults.update(overrides)
    return Invoice(**defaults)


def _make_payment_method(company_id, *, is_active=True, label="Carte perso") -> PaymentMethod:
    now = datetime.now(timezone.utc)
    return PaymentMethod(
        id=uuid4(),
        company_id=company_id,
        label=label,
        is_builtin=False,
        is_active=is_active,
        created_by=None,
        created_at=now,
        updated_at=now,
    )


def _make_repos():
    inv_repo = MagicMock(spec=IInvoiceRepository)
    inv_repo.update.side_effect = lambda inv: inv
    pm_repo = MagicMock(spec=IPaymentMethodRepository)
    return inv_repo, pm_repo


class TestBaselineRejection:
    """Sanity: the pre-existing behaviour still holds outside the carve-out."""

    def test_auto_generated_non_release_type_rejected_even_payment_method_only(self):
        """An auto-generated invoice of a different type (not released_funds) is
        never eligible for the carve-out — the baseline rejection still applies."""
        invoice = _make_release_invoice(type_=InvoiceType.MATERIALS_SERVICES)
        inv_repo, pm_repo = _make_repos()
        inv_repo.find_by_id.return_value = invoice
        use_case = UpdateInvoiceUseCase(inv_repo, payment_method_repo=pm_repo)

        with pytest.raises(AutoGeneratedInvoiceError):
            use_case.execute(UpdateInvoiceRequest(invoice_id=invoice.id, payment_method_id=uuid4()))

    def test_auto_generated_release_with_extra_field_rejected(self):
        """Any additional field alongside payment_method_id disqualifies the carve-out."""
        invoice = _make_release_invoice()
        inv_repo, pm_repo = _make_repos()
        inv_repo.find_by_id.return_value = invoice
        use_case = UpdateInvoiceUseCase(inv_repo, payment_method_repo=pm_repo)

        with pytest.raises(AutoGeneratedInvoiceError):
            use_case.execute(
                UpdateInvoiceRequest(
                    invoice_id=invoice.id,
                    payment_method_id=uuid4(),
                    recipient_name="Renamed",
                )
            )

    def test_auto_generated_release_with_cash_advance_flag_rejected(self):
        """The cash-advance flag is an edit like any other: it disqualifies the carve-out."""
        invoice = _make_release_invoice()
        inv_repo, pm_repo = _make_repos()
        inv_repo.find_by_id.return_value = invoice
        use_case = UpdateInvoiceUseCase(inv_repo, payment_method_repo=pm_repo)

        with pytest.raises(AutoGeneratedInvoiceError):
            use_case.execute(
                UpdateInvoiceRequest(
                    invoice_id=invoice.id,
                    payment_method_id=uuid4(),
                    is_cash_advance=True,
                )
            )

    def test_auto_generated_release_no_fields_at_all_rejected(self):
        """payment_method_id absent (_UNSET) — nothing to carve out; baseline applies."""
        invoice = _make_release_invoice()
        inv_repo, pm_repo = _make_repos()
        inv_repo.find_by_id.return_value = invoice
        use_case = UpdateInvoiceUseCase(inv_repo, payment_method_repo=pm_repo)

        with pytest.raises(AutoGeneratedInvoiceError):
            use_case.execute(UpdateInvoiceRequest(invoice_id=invoice.id))

    def test_non_auto_generated_release_unaffected_by_carveout_logic(self):
        """A manually-created released_funds invoice was never blocked — must stay that way."""
        invoice = _make_release_invoice(is_auto_generated=False)
        inv_repo, pm_repo = _make_repos()
        inv_repo.find_by_id.return_value = invoice
        use_case = UpdateInvoiceUseCase(inv_repo, payment_method_repo=pm_repo)

        result = use_case.execute(UpdateInvoiceRequest(invoice_id=invoice.id, recipient_name="Renamed"))

        assert result.recipient_name == "Renamed"


class TestCarveOutAllowsPaymentMethodOnlyEdit:
    def test_setting_a_valid_payment_method_succeeds(self):
        company_id = uuid4()
        invoice = _make_release_invoice()
        method = _make_payment_method(company_id)
        inv_repo, pm_repo = _make_repos()
        inv_repo.find_by_id.return_value = invoice
        pm_repo.find_by_id_for_update.return_value = method
        use_case = UpdateInvoiceUseCase(inv_repo, payment_method_repo=pm_repo)

        result = use_case.execute(
            UpdateInvoiceRequest(invoice_id=invoice.id, payment_method_id=method.id, company_id=company_id)
        )

        assert result.payment_method_id == str(method.id)
        assert result.payment_method_label == method.label
        # No other field was touched.
        assert result.recipient_name == invoice.recipient_name

    def test_explicit_null_clears_payment_method_and_is_allowed(self):
        """Explicit payment_method_id=None (clearing) also passes the carve-out."""
        invoice = _make_release_invoice(payment_method_id=uuid4(), payment_method_label="Old Label")
        inv_repo, pm_repo = _make_repos()
        inv_repo.find_by_id.return_value = invoice
        use_case = UpdateInvoiceUseCase(inv_repo, payment_method_repo=pm_repo)

        result = use_case.execute(UpdateInvoiceRequest(invoice_id=invoice.id, payment_method_id=None))

        assert result.payment_method_id is None
        assert result.payment_method_label is None

    def test_inactive_payment_method_still_raises(self):
        """The carve-out reuses the existing validation — inactive methods are still rejected."""
        company_id = uuid4()
        invoice = _make_release_invoice()
        method = _make_payment_method(company_id, is_active=False)
        inv_repo, pm_repo = _make_repos()
        inv_repo.find_by_id.return_value = invoice
        pm_repo.find_by_id_for_update.return_value = method
        use_case = UpdateInvoiceUseCase(inv_repo, payment_method_repo=pm_repo)

        with pytest.raises(PaymentMethodNotActiveError):
            use_case.execute(
                UpdateInvoiceRequest(invoice_id=invoice.id, payment_method_id=method.id, company_id=company_id)
            )

    def test_unknown_payment_method_still_raises(self):
        invoice = _make_release_invoice()
        inv_repo, pm_repo = _make_repos()
        inv_repo.find_by_id.return_value = invoice
        pm_repo.find_by_id_for_update.return_value = None
        use_case = UpdateInvoiceUseCase(inv_repo, payment_method_repo=pm_repo)

        with pytest.raises(PaymentMethodNotFoundError):
            use_case.execute(UpdateInvoiceRequest(invoice_id=invoice.id, payment_method_id=uuid4()))

    def test_cross_company_payment_method_still_raises(self):
        """The carve-out reuses the existing company-scope guard."""
        invoice_company_id = uuid4()
        other_company_id = uuid4()
        invoice = _make_release_invoice()
        method = _make_payment_method(other_company_id)
        inv_repo, pm_repo = _make_repos()
        inv_repo.find_by_id.return_value = invoice
        pm_repo.find_by_id_for_update.return_value = method
        use_case = UpdateInvoiceUseCase(inv_repo, payment_method_repo=pm_repo)

        with pytest.raises(ForbiddenCompanyError):
            use_case.execute(
                UpdateInvoiceRequest(invoice_id=invoice.id, payment_method_id=method.id, company_id=invoice_company_id)
            )
