"""add invoice_attachments table

Revision ID: 39cb464db20a
Revises: c1d2e3f4g5h6
Create Date: 2026-04-26 09:25:47.277911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cb464db20a'
down_revision = 'c1d2e3f4g5h6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('invoice_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_attachments_invoice_id'), ['invoice_id'], unique=False)


def downgrade():
    with op.batch_alter_table('invoice_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_attachments_invoice_id'))
    op.drop_table('invoice_attachments')
