"""Create auth tables for users, roles, and permissions

Revision ID: 7f6bfdbaee86
Revises:
Create Date: 2026-01-18 18:14:18.863178

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7f6bfdbaee86"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("resource", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.create_index("ix_permissions_resource_action", ["resource", "action"], unique=False)

    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # Note: For PostgreSQL, use: CREATE INDEX ix_users_email_lower ON users (LOWER(email));
    # SQLite doesn't support functional indexes, so we create a regular index here
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_email_lower", ["email"], unique=False)

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    # Add reverse indexes for efficient lookups
    with op.batch_alter_table("role_permissions", schema=None) as batch_op:
        batch_op.create_index("ix_role_permissions_role_id", ["role_id"], unique=False)
        batch_op.create_index("ix_role_permissions_permission_id", ["permission_id"], unique=False)

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    with op.batch_alter_table("role_permissions", schema=None) as batch_op:
        batch_op.drop_index("ix_role_permissions_permission_id")
        batch_op.drop_index("ix_role_permissions_role_id")
    op.drop_table("role_permissions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_email_lower")

    op.drop_table("users")
    op.drop_table("roles")
    with op.batch_alter_table("permissions", schema=None) as batch_op:
        batch_op.drop_index("ix_permissions_resource_action")

    op.drop_table("permissions")
    # ### end Alembic commands ###
