"""Invoice API routes."""

import dataclasses
from datetime import datetime
from typing import Tuple
from uuid import UUID

from flask import Response, jsonify, request
from flask_jwt_extended import get_jwt, jwt_required
from pydantic import ValidationError

from app.api._helpers.pydantic_errors import format_validation_error
from app.api._helpers.validation_error import validation_error_response
from app.api.openapi import openapi_doc
from app.api.v1.invoices import invoice_bp
from app.api.v1.invoices.schemas import (
    CreateInvoiceSchema,
    LaborPaymentsSummarySchema,
    ListInvoicesFilterQuery,
    UpdateInvoiceSchema,
    normalize_invoice_type_value,
)
from app.api.v1.projects.decorators import (
    require_permission,
    require_project_access,
    require_invoice_access,
)
from app.api.v1.projects.schemas import ErrorResponse
from app.application.invoice import (
    CreateInvoiceRequest,
    ListInvoicesRequest,
    UpdateInvoiceRequest,
)
from app.application.invoice.dtos import money
from app.application.invoice.get_labor_payments_summary_usecase import GetLaborPaymentsSummaryRequest
from app.domain.companies.exceptions import ForbiddenCompanyError
from app.domain.entities.invoice import InvoiceType
from app.domain.exceptions.invoice_exceptions import (
    AppliedAmountExceedsTargetError,
    AutoGeneratedInvoiceError,
    InvalidInvoiceDataError,
    InvoiceNotFoundError,
    InvoiceNumberConflictError,
    RefundExceedsSourceError,
    ServiceMonthNotAllowedError,
    WorkerLinkNotAllowedError,
    WorkerNotInProjectError,
)
from app.domain.payment_methods.exceptions import PaymentMethodNotActiveError, PaymentMethodNotFoundError
from app.infrastructure.database.models.invoice import InvoiceModel
from app.infrastructure.rate_limiter import limiter
from wiring import get_container

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _error_response(error: str, message: str, status_code: int) -> Tuple[Response, int]:
    """Return a standardised JSON error response."""
    return jsonify(ErrorResponse(error=error, message=message, status_code=status_code).model_dump()), status_code


def _validation_error_response(e: ValidationError) -> Tuple[Response, int]:
    """Convert a Pydantic ValidationError to a 400 error response.

    Delegates to the shared helper which handles empty ``loc`` tuples
    (e.g. from ``model_validator(mode='after')``).
    """
    return validation_error_response(e, status_code=400)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _get_project_company_id(project_id: UUID) -> "UUID | None":
    """Return the company_id for a project, or None if not found / no company.

    Queries the ProjectModel directly so we can access company_id without
    extending the domain Project entity or IProjectRepository.
    """
    from app import db
    from app.infrastructure.database.models.project import ProjectModel

    row = db.session.get(ProjectModel, project_id)
    return row.company_id if row is not None else None


def _get_project_company_name(project_id: UUID) -> "str | None":
    """Return the legal_name of the company attached to a project, or None.

    Used to surface company identity on the invoices list response so the
    frontend can display which company is responsible for the expenses.
    """
    from app import db
    from app.infrastructure.database.models.company import CompanyModel

    company_id = _get_project_company_id(project_id)
    if company_id is None:
        return None
    company = db.session.get(CompanyModel, company_id)
    return company.legal_name if company is not None else None


def _get_company_payment_method_ids(project_id: UUID) -> "set[UUID]":
    """Return the set of payment_method IDs flagged is_company_payment for the project's company.

    Fetched in one query; ignores is_active so soft-deleted methods are included.
    Returns an empty set when the project has no company.
    """
    from app import db
    from app.infrastructure.database.models.payment_method import PaymentMethodModel

    company_id = _get_project_company_id(project_id)
    if company_id is None:
        return set()
    rows = (
        db.session.query(PaymentMethodModel.id)
        .filter(
            PaymentMethodModel.company_id == company_id,
            PaymentMethodModel.is_company_payment.is_(True),
        )
        .all()
    )
    return {r[0] for r in rows}


def _get_personal_payment_method_ids(project_id: UUID) -> "set[UUID]":
    """Return the set of payment_method IDs flagged is_personal_payment for the project's company.

    Fetched in one query; ignores is_active so soft-deleted methods are included.
    Returns an empty set when the project has no company.
    """
    from app import db
    from app.infrastructure.database.models.payment_method import PaymentMethodModel

    company_id = _get_project_company_id(project_id)
    if company_id is None:
        return set()
    rows = (
        db.session.query(PaymentMethodModel.id)
        .filter(
            PaymentMethodModel.company_id == company_id,
            PaymentMethodModel.is_personal_payment.is_(True),
        )
        .all()
    )
    return {r[0] for r in rows}


def _load_company_and_personal_payment_method_ids(company_id: "UUID | None") -> "tuple[set[UUID], set[UUID]]":
    """Return (company_payment_ids, personal_payment_ids) for a company in one query.

    Single query over both flag columns, replacing the two separate queries
    _get_company_payment_method_ids / _get_personal_payment_method_ids would
    otherwise issue. Takes an already-resolved company_id so callers that need
    it for other purposes (e.g. company_name) don't re-resolve it. Returns two
    empty sets when company_id is None.
    """
    if company_id is None:
        return set(), set()
    from app import db
    from app.infrastructure.database.models.payment_method import PaymentMethodModel

    rows = (
        db.session.query(
            PaymentMethodModel.id,
            PaymentMethodModel.is_company_payment,
            PaymentMethodModel.is_personal_payment,
        )
        .filter(PaymentMethodModel.company_id == company_id)
        .all()
    )
    company_ids = {r[0] for r in rows if r[1]}
    personal_ids = {r[0] for r in rows if r[2]}
    return company_ids, personal_ids


def _enrich_refunds_invoice_number(invoice_dict: dict, refunds_invoice_id_str: "str | None") -> None:
    """Inject refunds_invoice_number into an invoice dict in-place.

    When refunds_invoice_id is present, fetches the linked invoice's number in one
    db.session.get call so the FE can display "Refund of INV-2026-0001" without
    a separate round-trip.  Sets None when the link is absent or target not found.
    """
    if not refunds_invoice_id_str:
        invoice_dict["refunds_invoice_number"] = None
        return
    from app import db
    from uuid import UUID as _UUID

    linked = db.session.get(InvoiceModel, _UUID(refunds_invoice_id_str))
    invoice_dict["refunds_invoice_number"] = linked.invoice_number if linked is not None else None


def _enrich_applied_to_invoice_number(invoice_dict: dict, applied_to_invoice_id_str: "str | None") -> None:
    """Inject applied_to_invoice_number into an invoice dict in-place.

    Mirrors _enrich_refunds_invoice_number: single db.session.get lookup so the FE can
    display "Applied to INV-2026-0001" for avoir-settled returns without a second
    round-trip. Sets None when the link is absent or the target is not found.
    """
    if not applied_to_invoice_id_str:
        invoice_dict["applied_to_invoice_number"] = None
        return
    from app import db
    from uuid import UUID as _UUID

    linked = db.session.get(InvoiceModel, _UUID(applied_to_invoice_id_str))
    invoice_dict["applied_to_invoice_number"] = linked.invoice_number if linked is not None else None


def _enrich_paid_with_returns(invoice_dict: dict, invoice_id_str: str) -> None:
    """Inject paid_with_returns into an invoice dict in-place.

    Lists the avoir return invoices whose applied_to_invoice_id points at this
    invoice, as [{"invoice_number": ..., "total_amount": ...}, ...]. Empty list when
    no returns are applied to it.
    """
    from uuid import UUID as _UUID

    invoice_uuid = _UUID(invoice_id_str)
    summaries = get_container().invoice_repository.applied_return_summaries([invoice_uuid])
    invoice_dict["paid_with_returns"] = summaries.get(invoice_uuid, [])


def _enrich_has_bank_refund(invoice_dict: dict, invoice_id_str: str, invoice_type: str) -> None:
    """Inject has_bank_refund into an invoice dict in-place.

    True only when this materials_services expense has ≥1 linked refund invoice
    (i.e. a supplier/vendor sent money back — "refunded by bank"). The company
    signal rides on refundable_status == 'refunded'. False for all other types.
    """
    if invoice_type != InvoiceType.MATERIALS_SERVICES.value:
        invoice_dict["has_bank_refund"] = False
        return
    from uuid import UUID as _UUID

    sources = get_container().invoice_repository.refund_source_ids([_UUID(invoice_id_str)])
    invoice_dict["has_bank_refund"] = _UUID(invoice_id_str) in sources


def _enrich_invoice_with_company_payment(
    invoice_dict: dict,
    payment_method_id_str: "str | None",
    company_pm_id_strs: "set[str]",
) -> dict:
    """Inject paid_by_company into an invoice dict in-place and return it.

    paid_by_company is True only when the invoice has a payment_method_id that
    belongs to the project's company and is flagged is_company_payment.
    False when payment_method_id is null or the project has no company.
    """
    invoice_dict["paid_by_company"] = payment_method_id_str is not None and payment_method_id_str in company_pm_id_strs
    return invoice_dict


def _enrich_invoice_with_personal_payment(
    invoice_dict: dict,
    payment_method_id_str: "str | None",
    personal_pm_id_strs: "set[str]",
) -> dict:
    """Inject paid_by_personal into an invoice dict in-place and return it.

    paid_by_personal is True only when the invoice has a payment_method_id that
    belongs to the project's company and is flagged is_personal_payment.
    False when payment_method_id is null or the project has no company.
    """
    invoice_dict["paid_by_personal"] = (
        payment_method_id_str is not None and payment_method_id_str in personal_pm_id_strs
    )
    return invoice_dict


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


@invoice_bp.route("/projects/<project_id>/invoices", methods=["GET"])
@openapi_doc(
    summary="List invoices for a project, optionally filtered by ?type=/?tag_id=/?service_month=/?worker_id=",
    query=ListInvoicesFilterQuery,
    tags=["invoices"],
)
@jwt_required()
@require_permission("project:read")
@require_project_access(write=False)
def list_invoices(project_id: str):
    """List invoices for a project, optionally filtered by ?type=/?tag_id=/?service_month=/?worker_id=."""
    invoice_type_param = normalize_invoice_type_value(request.args.get("type"))
    tag_id_param = request.args.get("tag_id")
    try:
        parsed_type = InvoiceType(invoice_type_param) if invoice_type_param else None
    except ValueError:
        valid = ", ".join(t.value for t in InvoiceType)
        return _error_response(
            "ValidationError",
            f"Invalid type '{invoice_type_param}'. Must be one of: {valid}",
            400,
        )

    # service_month/worker_id are the labor-payments drill-down filters — validated
    # via Pydantic so malformed input returns 422 (mirrors ExportLaborQuery).
    try:
        filters = ListInvoicesFilterQuery(
            service_month=request.args.get("service_month"),
            worker_id=request.args.get("worker_id"),
        )
    except ValidationError as e:
        return format_validation_error(e)

    service_month_date = (
        datetime.strptime(filters.service_month, "%Y-%m").date().replace(day=1) if filters.service_month else None
    )

    container = get_container()
    try:
        results = container.list_invoices_usecase.execute(
            ListInvoicesRequest(
                project_id=UUID(project_id),
                invoice_type=parsed_type,
                tag_id=UUID(tag_id_param) if tag_id_param else None,
                service_month=service_month_date,
                worker_id=filters.worker_id,
            )
        )
    except ValueError as e:
        return _error_response("ValidationError", str(e), 400)

    project_uuid = UUID(project_id)

    # One scan for the released-funds split, one scan for the spent split — down from
    # four whole-table aggregations (sum_funds_released + sum_funds_released_split +
    # sum_company_spent + sum_personal_spent) to two. funds_released_total is derived
    # from the RAW (pre-quantization) split components so it exactly reconciles with
    # their sum, per the port's documented invariant.
    funds_released_company_raw, funds_released_personal_raw = container.invoice_repository.sum_funds_released_split(
        project_uuid
    )
    funds_released_total = money(funds_released_company_raw + funds_released_personal_raw)
    funds_released_company_total = money(funds_released_company_raw)
    funds_released_personal_total = money(funds_released_personal_raw)

    company_spent_raw, personal_spent_raw = container.invoice_repository.sum_spent_split(project_uuid)
    company_spent_total = money(company_spent_raw)
    personal_spent_total = money(personal_spent_raw)

    # Resolve company once; reuse for company_name, paid_by_company/paid_by_personal
    # enrichment, and the payment-method-id lookups below (was resolved 3x before).
    from app import db
    from app.infrastructure.database.models.company import CompanyModel

    _company_id = _get_project_company_id(project_uuid)
    if _company_id is not None:
        _company_row = db.session.get(CompanyModel, _company_id)
        company_name = _company_row.legal_name if _company_row is not None else None
    else:
        company_name = None

    # Single query over both flag columns (was two separate queries); membership-test
    # per invoice row. IDs come back as UUIDs from the DB; compare as strings to
    # match InvoiceResponse.payment_method_id.
    _company_pm_ids, _personal_pm_ids = _load_company_and_personal_payment_method_ids(_company_id)
    company_pm_id_strs: set[str] = {str(uid) for uid in _company_pm_ids}
    personal_pm_id_strs: set[str] = {str(uid) for uid in _personal_pm_ids}

    invoice_dicts = []
    for r in results:
        d = dataclasses.asdict(r)
        # r.payment_method_id is a str (InvoiceResponse serialises it that way)
        _enrich_invoice_with_company_payment(d, r.payment_method_id, company_pm_id_strs)
        _enrich_invoice_with_personal_payment(d, r.payment_method_id, personal_pm_id_strs)
        invoice_dicts.append(d)

    # Batch-enrich refunds_invoice_number in one query (no N+1) so the list/mobile
    # views can render "Refund of <number>" for linked refund invoices.
    link_id_strs = {r.refunds_invoice_id for r in results if r.refunds_invoice_id}
    number_by_id: dict[str, str] = {}
    if link_id_strs:
        rows = (
            db.session.query(InvoiceModel.id, InvoiceModel.invoice_number)
            .filter(InvoiceModel.id.in_([UUID(x) for x in link_id_strs]))
            .all()
        )
        number_by_id = {str(_id): _num for _id, _num in rows}
    for d, r in zip(invoice_dicts, results):
        d["refunds_invoice_number"] = number_by_id.get(r.refunds_invoice_id) if r.refunds_invoice_id else None

    # Batch-enrich has_bank_refund (one query) for the materials_services rows so the
    # list/mobile views can show the company-vs-bank refund-source indicator.
    ms_ids = [UUID(r.id) for r in results if r.type == InvoiceType.MATERIALS_SERVICES.value]
    bank_refunded = container.invoice_repository.refund_source_ids(ms_ids) if ms_ids else set()
    for d, r in zip(invoice_dicts, results):
        d["has_bank_refund"] = r.type == InvoiceType.MATERIALS_SERVICES.value and UUID(r.id) in bank_refunded

    # Batch-enrich applied_to_invoice_number (mirrors refunds_invoice_number above) so
    # the list/mobile views can render "Applied to <number>" for avoir-linked returns.
    applied_link_id_strs = {r.applied_to_invoice_id for r in results if r.applied_to_invoice_id}
    applied_number_by_id: dict[str, str] = {}
    if applied_link_id_strs:
        rows = (
            db.session.query(InvoiceModel.id, InvoiceModel.invoice_number)
            .filter(InvoiceModel.id.in_([UUID(x) for x in applied_link_id_strs]))
            .all()
        )
        applied_number_by_id = {str(_id): _num for _id, _num in rows}
    for d, r in zip(invoice_dicts, results):
        d["applied_to_invoice_number"] = (
            applied_number_by_id.get(r.applied_to_invoice_id) if r.applied_to_invoice_id else None
        )

    # Reverse enrichment: paid_with_returns — for each row, the avoir returns applied to
    # it. One batch query over the whole page's ids (no N+1).
    page_ids = [UUID(r.id) for r in results]
    applied_summaries = container.invoice_repository.applied_return_summaries(page_ids) if page_ids else {}
    for d, r in zip(invoice_dicts, results):
        d["paid_with_returns"] = applied_summaries.get(UUID(r.id), [])

    return jsonify(
        {
            "invoices": invoice_dicts,
            "total": len(invoice_dicts),
            "funds_released_total": funds_released_total,
            "company_spent_total": company_spent_total,
            "funds_released_company_total": funds_released_company_total,
            "funds_released_personal_total": funds_released_personal_total,
            "personal_spent_total": personal_spent_total,
            "company_name": company_name,
        }
    )


@invoice_bp.route("/projects/<project_id>/labor-payments-summary", methods=["GET"])
@openapi_doc(
    summary="Aggregate paid labor amounts per service month and worker",
    responses={200: LaborPaymentsSummarySchema},
    tags=["invoices"],
)
@jwt_required()
@require_permission("project:read")
@require_project_access(write=False)
def get_labor_payments_summary(project_id: str):
    """Aggregate paid amounts per (service_month, worker) for the project's labor invoices."""
    result = get_container().get_labor_payments_summary_usecase.execute(
        GetLaborPaymentsSummaryRequest(project_id=UUID(project_id))
    )
    schema = LaborPaymentsSummarySchema.model_validate(dataclasses.asdict(result))
    return jsonify(schema.model_dump())


@invoice_bp.route("/projects/<project_id>/invoices", methods=["POST"])
@openapi_doc(
    summary="Create a new invoice for a project",
    request=CreateInvoiceSchema,
    tags=["invoices"],
)
@jwt_required()
@limiter.limit("20 per minute")
@require_permission("project:manage_invoices")
@require_project_access(write=True)
def create_invoice(project_id: str):
    """Create a new invoice for a project."""
    try:
        data = CreateInvoiceSchema(**request.get_json())
    except ValidationError as e:
        return _validation_error_response(e)

    jwt_claims = get_jwt()
    # JWT subject holds the authenticated user's UUID
    created_by = UUID(jwt_claims["sub"])

    project_uuid = UUID(project_id)
    company_id = _get_project_company_id(project_uuid)

    try:
        result = get_container().create_invoice_usecase.execute(
            CreateInvoiceRequest(
                project_id=project_uuid,
                created_by=created_by,
                type=InvoiceType(data.type),
                issue_date=data.issue_date,  # already a date object from Pydantic
                recipient_name=data.recipient_name,
                recipient_address=data.recipient_address,
                notes=data.notes,
                items=[item.model_dump() for item in data.items],
                payment_method_id=data.payment_method_id,
                company_id=company_id,
                tag_id=data.tag_id,
                refunds_invoice_id=data.refunds_invoice_id,
                service_month=data.service_month,
                settled_via=data.settled_via,
                applied_to_invoice_id=data.applied_to_invoice_id,
                worker_id=data.worker_id,
            )
        )
    except InvoiceNumberConflictError:
        return _error_response("Conflict", "Invoice number conflict, please retry", 409)
    except PaymentMethodNotFoundError:
        return _error_response("NotFound", "Payment method not found", 404)
    except PaymentMethodNotActiveError:
        return _error_response("Conflict", "Payment method is inactive and cannot be used", 409)
    except ForbiddenCompanyError:
        return _error_response("Forbidden", "Payment method belongs to a different company", 403)
    except RefundExceedsSourceError as e:
        # Distinct code so the frontend can show a localized "remaining refundable" message.
        return _error_response("RefundExceedsSource", str(e), 400)
    except AppliedAmountExceedsTargetError as e:
        # Distinct code so the frontend can show a localized "remaining applicable" message.
        return _error_response("AppliedExceedsTarget", str(e), 400)
    except ServiceMonthNotAllowedError:
        return _error_response("service_month_not_allowed", "service_month is only allowed on labor invoices", 400)
    except WorkerLinkNotAllowedError:
        return _error_response("worker_link_not_allowed", "worker_id is only allowed on labor invoices", 400)
    except WorkerNotInProjectError:
        return _error_response("worker_not_in_project", "Worker does not belong to this project", 400)
    except ValueError as e:
        return _error_response("ValidationError", str(e), 400)
    except InvalidInvoiceDataError as e:
        return _error_response("ValidationError", str(e), 400)

    company_pm_id_strs = {str(uid) for uid in _get_company_payment_method_ids(project_uuid)}
    personal_pm_id_strs = {str(uid) for uid in _get_personal_payment_method_ids(project_uuid)}
    d = dataclasses.asdict(result)
    _enrich_invoice_with_company_payment(d, result.payment_method_id, company_pm_id_strs)
    _enrich_invoice_with_personal_payment(d, result.payment_method_id, personal_pm_id_strs)
    _enrich_refunds_invoice_number(d, result.refunds_invoice_id)
    _enrich_applied_to_invoice_number(d, result.applied_to_invoice_id)
    _enrich_paid_with_returns(d, result.id)
    _enrich_has_bank_refund(d, result.id, result.type)
    return jsonify(d), 201


@invoice_bp.route("/projects/<project_id>/invoices/<invoice_id>", methods=["GET"])
@openapi_doc(summary="Retrieve a single invoice by ID, scoped to the project", tags=["invoices"])
@jwt_required()
@require_permission("project:read")
@require_invoice_access(write=False)
def get_invoice(project_id: str, invoice_id: str):
    """Retrieve a single invoice by ID, scoped to the project."""
    try:
        result = get_container().get_invoice_usecase.execute(UUID(invoice_id))
    except InvoiceNotFoundError:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)
    except ValueError as e:
        return _error_response("ValidationError", str(e), 400)

    # Verify invoice belongs to the requested project (prevents cross-project access)
    if result.project_id != project_id:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)

    project_uuid = UUID(project_id)
    company_pm_id_strs = {str(uid) for uid in _get_company_payment_method_ids(project_uuid)}
    personal_pm_id_strs = {str(uid) for uid in _get_personal_payment_method_ids(project_uuid)}
    d = dataclasses.asdict(result)
    _enrich_invoice_with_company_payment(d, result.payment_method_id, company_pm_id_strs)
    _enrich_invoice_with_personal_payment(d, result.payment_method_id, personal_pm_id_strs)
    _enrich_refunds_invoice_number(d, result.refunds_invoice_id)
    _enrich_applied_to_invoice_number(d, result.applied_to_invoice_id)
    _enrich_paid_with_returns(d, result.id)
    _enrich_has_bank_refund(d, result.id, result.type)
    return jsonify(d)


@invoice_bp.route("/projects/<project_id>/invoices/<invoice_id>", methods=["PUT"])
@openapi_doc(
    summary="Partially update an invoice",
    request=UpdateInvoiceSchema,
    tags=["invoices"],
)
@jwt_required()
@limiter.limit("20 per minute")
@require_permission("project:manage_invoices")
@require_invoice_access(write=True)
def update_invoice(project_id: str, invoice_id: str):
    """Partially update an invoice."""
    try:
        data = UpdateInvoiceSchema(**request.get_json())
    except ValidationError as e:
        return _validation_error_response(e)

    # Build kwargs — only pass fields the caller provided.
    # issue_date is already a date object from Pydantic (no manual conversion needed).
    # payment_method_id, tag_id, refunds_invoice_id, service_month, settled_via,
    # applied_to_invoice_id, and worker_id are handled separately: use exclude_unset
    # so we can distinguish "not provided" (absent) from "explicitly null".
    provided_fields = data.model_dump(exclude_unset=True)
    sentinel_fields = (
        "payment_method_id",
        "tag_id",
        "refunds_invoice_id",
        "service_month",
        "settled_via",
        "applied_to_invoice_id",
        "worker_id",
    )
    update_kwargs = {k: v for k, v in provided_fields.items() if k not in sentinel_fields and v is not None}
    # type arrives as a validated string literal; the use case and domain entity
    # operate on the InvoiceType enum, so promote it here (mirrors create flow).
    if "type" in update_kwargs:
        update_kwargs["type"] = InvoiceType(update_kwargs["type"])

    # Verify invoice belongs to the requested project before updating
    try:
        existing = get_container().get_invoice_usecase.execute(UUID(invoice_id))
    except InvoiceNotFoundError:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)

    if existing.project_id != project_id:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)

    invoice_uuid = UUID(invoice_id)
    project_uuid = UUID(project_id)

    # Determine payment_method, tag_id, refunds_invoice_id, service_month, settled_via,
    # applied_to_invoice_id, and worker_id sentinels: _UNSET if not in request body;
    # else the provided value (which may be None = clear).
    from app.application.invoice.update_invoice import _UNSET

    pm_id = provided_fields["payment_method_id"] if "payment_method_id" in provided_fields else _UNSET
    tag_id_val = provided_fields["tag_id"] if "tag_id" in provided_fields else _UNSET
    refunds_id_val = provided_fields["refunds_invoice_id"] if "refunds_invoice_id" in provided_fields else _UNSET
    service_month_val = provided_fields["service_month"] if "service_month" in provided_fields else _UNSET
    settled_via_val = provided_fields["settled_via"] if "settled_via" in provided_fields else _UNSET
    applied_to_val = provided_fields["applied_to_invoice_id"] if "applied_to_invoice_id" in provided_fields else _UNSET
    worker_id_val = provided_fields["worker_id"] if "worker_id" in provided_fields else _UNSET

    company_id = _get_project_company_id(project_uuid) if pm_id is not _UNSET else None

    update_req = UpdateInvoiceRequest(
        invoice_id=invoice_uuid,
        payment_method_id=pm_id,
        company_id=company_id,
        tag_id=tag_id_val,
        refunds_invoice_id=refunds_id_val,
        service_month=service_month_val,
        settled_via=settled_via_val,
        applied_to_invoice_id=applied_to_val,
        worker_id=worker_id_val,
        **update_kwargs,
    )

    try:
        result = get_container().update_invoice_usecase.execute(update_req)
    except AutoGeneratedInvoiceError as e:
        return _error_response("Forbidden", str(e), 403)
    except InvoiceNotFoundError:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)
    except PaymentMethodNotFoundError:
        return _error_response("NotFound", "Payment method not found", 404)
    except PaymentMethodNotActiveError:
        return _error_response("Conflict", "Payment method is inactive and cannot be used", 409)
    except ForbiddenCompanyError:
        return _error_response("Forbidden", "Payment method belongs to a different company", 403)
    except RefundExceedsSourceError as e:
        # Distinct code so the frontend can show a localized "remaining refundable" message.
        return _error_response("RefundExceedsSource", str(e), 400)
    except AppliedAmountExceedsTargetError as e:
        # Distinct code so the frontend can show a localized "remaining applicable" message.
        return _error_response("AppliedExceedsTarget", str(e), 400)
    except ServiceMonthNotAllowedError:
        return _error_response("service_month_not_allowed", "service_month is only allowed on labor invoices", 400)
    except WorkerLinkNotAllowedError:
        return _error_response("worker_link_not_allowed", "worker_id is only allowed on labor invoices", 400)
    except WorkerNotInProjectError:
        return _error_response("worker_not_in_project", "Worker does not belong to this project", 400)
    except (ValueError, InvalidInvoiceDataError) as e:
        return _error_response("ValidationError", str(e), 400)

    company_pm_id_strs = {str(uid) for uid in _get_company_payment_method_ids(project_uuid)}
    personal_pm_id_strs = {str(uid) for uid in _get_personal_payment_method_ids(project_uuid)}
    d = dataclasses.asdict(result)
    _enrich_invoice_with_company_payment(d, result.payment_method_id, company_pm_id_strs)
    _enrich_invoice_with_personal_payment(d, result.payment_method_id, personal_pm_id_strs)
    _enrich_refunds_invoice_number(d, result.refunds_invoice_id)
    _enrich_applied_to_invoice_number(d, result.applied_to_invoice_id)
    _enrich_paid_with_returns(d, result.id)
    _enrich_has_bank_refund(d, result.id, result.type)
    return jsonify(d)


@invoice_bp.route("/projects/<project_id>/invoices/<invoice_id>", methods=["DELETE"])
@openapi_doc(summary="Delete an invoice by ID, scoped to the project", tags=["invoices"])
@jwt_required()
@limiter.limit("20 per minute")
@require_permission("project:manage_invoices")
@require_invoice_access(write=True)
def delete_invoice(project_id: str, invoice_id: str):
    """Delete an invoice by ID, scoped to the project."""
    # Verify invoice belongs to the requested project before deleting
    try:
        existing = get_container().get_invoice_usecase.execute(UUID(invoice_id))
    except InvoiceNotFoundError:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)

    if existing.project_id != project_id:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)

    try:
        get_container().delete_invoice_usecase.execute(UUID(invoice_id))
    except AutoGeneratedInvoiceError as e:
        return _error_response("Forbidden", str(e), 403)
    except InvoiceNotFoundError:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)
    except ValueError as e:
        return _error_response("ValidationError", str(e), 400)

    return "", 204
