"""Invoice API routes."""

import dataclasses
from typing import Tuple
from uuid import UUID

from flask import Response, jsonify, request
from flask_jwt_extended import get_jwt, jwt_required
from pydantic import ValidationError

from app.api._helpers.validation_error import validation_error_response
from app.api.openapi import openapi_doc
from app.api.v1.invoices import invoice_bp
from app.api.v1.invoices.schemas import CreateInvoiceSchema, UpdateInvoiceSchema
from app.api.v1.projects.decorators import (
    require_permission,
    require_project_access,
    require_invoice_access,
)
from app.api.v1.projects.schemas import ErrorResponse
from app.application.invoice import (
    CreateInvoiceRequest,
    ListInvoicesRequest,
    UpdateInvoiceRequest,
)
from app.application.invoice.dtos import money
from app.domain.companies.exceptions import ForbiddenCompanyError
from app.domain.entities.invoice import InvoiceType
from app.domain.exceptions.invoice_exceptions import (
    AutoGeneratedInvoiceError,
    InvalidInvoiceDataError,
    InvoiceNotFoundError,
    InvoiceNumberConflictError,
    RefundExceedsSourceError,
    ServiceMonthNotAllowedError,
)
from app.domain.payment_methods.exceptions import PaymentMethodNotActiveError, PaymentMethodNotFoundError
from app.infrastructure.database.models.invoice import InvoiceModel
from app.infrastructure.rate_limiter import limiter
from wiring import get_container

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _error_response(error: str, message: str, status_code: int) -> Tuple[Response, int]:
    """Return a standardised JSON error response."""
    return jsonify(ErrorResponse(error=error, message=message, status_code=status_code).model_dump()), status_code


def _validation_error_response(e: ValidationError) -> Tuple[Response, int]:
    """Convert a Pydantic ValidationError to a 400 error response.

    Delegates to the shared helper which handles empty ``loc`` tuples
    (e.g. from ``model_validator(mode='after')``).
    """
    return validation_error_response(e, status_code=400)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _get_project_company_id(project_id: UUID) -> "UUID | None":
    """Return the company_id for a project, or None if not found / no company.

    Queries the ProjectModel directly so we can access company_id without
    extending the domain Project entity or IProjectRepository.
    """
    from app import db
    from app.infrastructure.database.models.project import ProjectModel

    row = db.session.get(ProjectModel, project_id)
    return row.company_id if row is not None else None


def _get_project_company_name(project_id: UUID) -> "str | None":
    """Return the legal_name of the company attached to a project, or None.

    Used to surface company identity on the invoices list response so the
    frontend can display which company is responsible for the expenses.
    """
    from app import db
    from app.infrastructure.database.models.company import CompanyModel

    company_id = _get_project_company_id(project_id)
    if company_id is None:
        return None
    company = db.session.get(CompanyModel, company_id)
    return company.legal_name if company is not None else None


def _get_company_payment_method_ids(project_id: UUID) -> "set[UUID]":
    """Return the set of payment_method IDs flagged is_company_payment for the project's company.

    Fetched in one query; ignores is_active so soft-deleted methods are included.
    Returns an empty set when the project has no company.
    """
    from app import db
    from app.infrastructure.database.models.payment_method import PaymentMethodModel

    company_id = _get_project_company_id(project_id)
    if company_id is None:
        return set()
    rows = (
        db.session.query(PaymentMethodModel.id)
        .filter(
            PaymentMethodModel.company_id == company_id,
            PaymentMethodModel.is_company_payment.is_(True),
        )
        .all()
    )
    return {r[0] for r in rows}


def _enrich_refunds_invoice_number(invoice_dict: dict, refunds_invoice_id_str: "str | None") -> None:
    """Inject refunds_invoice_number into an invoice dict in-place.

    When refunds_invoice_id is present, fetches the linked invoice's number in one
    db.session.get call so the FE can display "Refund of INV-2026-0001" without
    a separate round-trip.  Sets None when the link is absent or target not found.
    """
    if not refunds_invoice_id_str:
        invoice_dict["refunds_invoice_number"] = None
        return
    from app import db
    from uuid import UUID as _UUID

    linked = db.session.get(InvoiceModel, _UUID(refunds_invoice_id_str))
    invoice_dict["refunds_invoice_number"] = linked.invoice_number if linked is not None else None


def _enrich_has_bank_refund(invoice_dict: dict, invoice_id_str: str, invoice_type: str) -> None:
    """Inject has_bank_refund into an invoice dict in-place.

    True only when this materials_services expense has ≥1 linked refund invoice
    (i.e. a supplier/vendor sent money back — "refunded by bank"). The company
    signal rides on refundable_status == 'refunded'. False for all other types.
    """
    if invoice_type != InvoiceType.MATERIALS_SERVICES.value:
        invoice_dict["has_bank_refund"] = False
        return
    from uuid import UUID as _UUID

    sources = get_container().invoice_repository.refund_source_ids([_UUID(invoice_id_str)])
    invoice_dict["has_bank_refund"] = _UUID(invoice_id_str) in sources


def _enrich_invoice_with_company_payment(
    invoice_dict: dict,
    payment_method_id_str: "str | None",
    company_pm_id_strs: "set[str]",
) -> dict:
    """Inject paid_by_company into an invoice dict in-place and return it.

    paid_by_company is True only when the invoice has a payment_method_id that
    belongs to the project's company and is flagged is_company_payment.
    False when payment_method_id is null or the project has no company.
    """
    invoice_dict["paid_by_company"] = payment_method_id_str is not None and payment_method_id_str in company_pm_id_strs
    return invoice_dict


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


@invoice_bp.route("/projects/<project_id>/invoices", methods=["GET"])
@openapi_doc(summary="List invoices for a project, optionally filtered by ?type=", tags=["invoices"])
@jwt_required()
@require_permission("project:read")
@require_project_access(write=False)
def list_invoices(project_id: str):
    """List invoices for a project, optionally filtered by ?type=."""
    invoice_type_param = request.args.get("type")
    tag_id_param = request.args.get("tag_id")
    try:
        parsed_type = InvoiceType(invoice_type_param) if invoice_type_param else None
    except ValueError:
        return _error_response(
            "ValidationError",
            f"Invalid type '{invoice_type_param}'. Must be one of: client, labor, supplier",
            400,
        )

    container = get_container()
    try:
        results = container.list_invoices_usecase.execute(
            ListInvoicesRequest(
                project_id=UUID(project_id),
                invoice_type=parsed_type,
                tag_id=UUID(tag_id_param) if tag_id_param else None,
            )
        )
    except ValueError as e:
        return _error_response("ValidationError", str(e), 400)

    project_uuid = UUID(project_id)
    funds_released_total = money(container.invoice_repository.sum_funds_released(project_uuid))
    company_spent_total = money(container.invoice_repository.sum_company_spent(project_uuid))

    # Resolve company once; reuse for both company_name and paid_by_company enrichment.
    from app import db
    from app.infrastructure.database.models.company import CompanyModel

    _company_id = _get_project_company_id(project_uuid)
    if _company_id is not None:
        _company_row = db.session.get(CompanyModel, _company_id)
        company_name = _company_row.legal_name if _company_row is not None else None
    else:
        company_name = None

    # One query to get all company-payment method IDs; membership-test per invoice row.
    # IDs come back as UUIDs from the DB; compare as strings to match InvoiceResponse.payment_method_id.
    if _company_id is not None:
        from app.infrastructure.database.models.payment_method import PaymentMethodModel

        _pm_rows = (
            db.session.query(PaymentMethodModel.id)
            .filter(
                PaymentMethodModel.company_id == _company_id,
                PaymentMethodModel.is_company_payment.is_(True),
            )
            .all()
        )
        company_pm_id_strs: set[str] = {str(r[0]) for r in _pm_rows}
    else:
        company_pm_id_strs = set()

    invoice_dicts = []
    for r in results:
        d = dataclasses.asdict(r)
        # r.payment_method_id is a str (InvoiceResponse serialises it that way)
        _enrich_invoice_with_company_payment(d, r.payment_method_id, company_pm_id_strs)
        invoice_dicts.append(d)

    # Batch-enrich refunds_invoice_number in one query (no N+1) so the list/mobile
    # views can render "Refund of <number>" for linked refund invoices.
    link_id_strs = {r.refunds_invoice_id for r in results if r.refunds_invoice_id}
    number_by_id: dict[str, str] = {}
    if link_id_strs:
        rows = (
            db.session.query(InvoiceModel.id, InvoiceModel.invoice_number)
            .filter(InvoiceModel.id.in_([UUID(x) for x in link_id_strs]))
            .all()
        )
        number_by_id = {str(_id): _num for _id, _num in rows}
    for d, r in zip(invoice_dicts, results):
        d["refunds_invoice_number"] = number_by_id.get(r.refunds_invoice_id) if r.refunds_invoice_id else None

    # Batch-enrich has_bank_refund (one query) for the materials_services rows so the
    # list/mobile views can show the company-vs-bank refund-source indicator.
    ms_ids = [UUID(r.id) for r in results if r.type == InvoiceType.MATERIALS_SERVICES.value]
    bank_refunded = container.invoice_repository.refund_source_ids(ms_ids) if ms_ids else set()
    for d, r in zip(invoice_dicts, results):
        d["has_bank_refund"] = r.type == InvoiceType.MATERIALS_SERVICES.value and UUID(r.id) in bank_refunded

    return jsonify(
        {
            "invoices": invoice_dicts,
            "total": len(invoice_dicts),
            "funds_released_total": funds_released_total,
            "company_spent_total": company_spent_total,
            "company_name": company_name,
        }
    )


@invoice_bp.route("/projects/<project_id>/invoices", methods=["POST"])
@openapi_doc(
    summary="Create a new invoice for a project",
    request=CreateInvoiceSchema,
    tags=["invoices"],
)
@jwt_required()
@limiter.limit("20 per minute")
@require_permission("project:manage_invoices")
@require_project_access(write=True)
def create_invoice(project_id: str):
    """Create a new invoice for a project."""
    try:
        data = CreateInvoiceSchema(**request.get_json())
    except ValidationError as e:
        return _validation_error_response(e)

    jwt_claims = get_jwt()
    # JWT subject holds the authenticated user's UUID
    created_by = UUID(jwt_claims["sub"])

    project_uuid = UUID(project_id)
    company_id = _get_project_company_id(project_uuid)

    try:
        result = get_container().create_invoice_usecase.execute(
            CreateInvoiceRequest(
                project_id=project_uuid,
                created_by=created_by,
                type=InvoiceType(data.type),
                issue_date=data.issue_date,  # already a date object from Pydantic
                recipient_name=data.recipient_name,
                recipient_address=data.recipient_address,
                notes=data.notes,
                items=[item.model_dump() for item in data.items],
                payment_method_id=data.payment_method_id,
                company_id=company_id,
                tag_id=data.tag_id,
                refunds_invoice_id=data.refunds_invoice_id,
                service_month=data.service_month,
            )
        )
    except InvoiceNumberConflictError:
        return _error_response("Conflict", "Invoice number conflict, please retry", 409)
    except PaymentMethodNotFoundError:
        return _error_response("NotFound", "Payment method not found", 404)
    except PaymentMethodNotActiveError:
        return _error_response("Conflict", "Payment method is inactive and cannot be used", 409)
    except ForbiddenCompanyError:
        return _error_response("Forbidden", "Payment method belongs to a different company", 403)
    except RefundExceedsSourceError as e:
        # Distinct code so the frontend can show a localized "remaining refundable" message.
        return _error_response("RefundExceedsSource", str(e), 400)
    except ServiceMonthNotAllowedError:
        return _error_response("service_month_not_allowed", "service_month is only allowed on labor invoices", 400)
    except ValueError as e:
        return _error_response("ValidationError", str(e), 400)
    except InvalidInvoiceDataError as e:
        return _error_response("ValidationError", str(e), 400)

    d = dataclasses.asdict(result)
    _enrich_refunds_invoice_number(d, result.refunds_invoice_id)
    _enrich_has_bank_refund(d, result.id, result.type)
    return jsonify(d), 201


@invoice_bp.route("/projects/<project_id>/invoices/<invoice_id>", methods=["GET"])
@openapi_doc(summary="Retrieve a single invoice by ID, scoped to the project", tags=["invoices"])
@jwt_required()
@require_permission("project:read")
@require_invoice_access(write=False)
def get_invoice(project_id: str, invoice_id: str):
    """Retrieve a single invoice by ID, scoped to the project."""
    try:
        result = get_container().get_invoice_usecase.execute(UUID(invoice_id))
    except InvoiceNotFoundError:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)
    except ValueError as e:
        return _error_response("ValidationError", str(e), 400)

    # Verify invoice belongs to the requested project (prevents cross-project access)
    if result.project_id != project_id:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)

    project_uuid = UUID(project_id)
    company_pm_id_strs = {str(uid) for uid in _get_company_payment_method_ids(project_uuid)}
    d = dataclasses.asdict(result)
    _enrich_invoice_with_company_payment(d, result.payment_method_id, company_pm_id_strs)
    _enrich_refunds_invoice_number(d, result.refunds_invoice_id)
    _enrich_has_bank_refund(d, result.id, result.type)
    return jsonify(d)


@invoice_bp.route("/projects/<project_id>/invoices/<invoice_id>", methods=["PUT"])
@openapi_doc(
    summary="Partially update an invoice",
    request=UpdateInvoiceSchema,
    tags=["invoices"],
)
@jwt_required()
@limiter.limit("20 per minute")
@require_permission("project:manage_invoices")
@require_invoice_access(write=True)
def update_invoice(project_id: str, invoice_id: str):
    """Partially update an invoice."""
    try:
        data = UpdateInvoiceSchema(**request.get_json())
    except ValidationError as e:
        return _validation_error_response(e)

    # Build kwargs — only pass fields the caller provided.
    # issue_date is already a date object from Pydantic (no manual conversion needed).
    # payment_method_id, tag_id, refunds_invoice_id, and service_month are handled
    # separately: use exclude_unset so we can distinguish "not provided" (absent)
    # from "explicitly null".
    provided_fields = data.model_dump(exclude_unset=True)
    update_kwargs = {
        k: v
        for k, v in provided_fields.items()
        if k not in ("payment_method_id", "tag_id", "refunds_invoice_id", "service_month") and v is not None
    }
    # type arrives as a validated string literal; the use case and domain entity
    # operate on the InvoiceType enum, so promote it here (mirrors create flow).
    if "type" in update_kwargs:
        update_kwargs["type"] = InvoiceType(update_kwargs["type"])

    # Verify invoice belongs to the requested project before updating
    try:
        existing = get_container().get_invoice_usecase.execute(UUID(invoice_id))
    except InvoiceNotFoundError:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)

    if existing.project_id != project_id:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)

    invoice_uuid = UUID(invoice_id)
    project_uuid = UUID(project_id)

    # Determine payment_method, tag_id, refunds_invoice_id, and service_month sentinels:
    # _UNSET if not in request body; else the provided value (which may be None = clear).
    from app.application.invoice.update_invoice import _UNSET

    pm_id = provided_fields["payment_method_id"] if "payment_method_id" in provided_fields else _UNSET
    tag_id_val = provided_fields["tag_id"] if "tag_id" in provided_fields else _UNSET
    refunds_id_val = provided_fields["refunds_invoice_id"] if "refunds_invoice_id" in provided_fields else _UNSET
    service_month_val = provided_fields["service_month"] if "service_month" in provided_fields else _UNSET

    company_id = _get_project_company_id(project_uuid) if pm_id is not _UNSET else None

    update_req = UpdateInvoiceRequest(
        invoice_id=invoice_uuid,
        payment_method_id=pm_id,
        company_id=company_id,
        tag_id=tag_id_val,
        refunds_invoice_id=refunds_id_val,
        service_month=service_month_val,
        **update_kwargs,
    )

    try:
        result = get_container().update_invoice_usecase.execute(update_req)
    except AutoGeneratedInvoiceError as e:
        return _error_response("Forbidden", str(e), 403)
    except InvoiceNotFoundError:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)
    except PaymentMethodNotFoundError:
        return _error_response("NotFound", "Payment method not found", 404)
    except PaymentMethodNotActiveError:
        return _error_response("Conflict", "Payment method is inactive and cannot be used", 409)
    except ForbiddenCompanyError:
        return _error_response("Forbidden", "Payment method belongs to a different company", 403)
    except RefundExceedsSourceError as e:
        # Distinct code so the frontend can show a localized "remaining refundable" message.
        return _error_response("RefundExceedsSource", str(e), 400)
    except ServiceMonthNotAllowedError:
        return _error_response("service_month_not_allowed", "service_month is only allowed on labor invoices", 400)
    except (ValueError, InvalidInvoiceDataError) as e:
        return _error_response("ValidationError", str(e), 400)

    company_pm_id_strs = {str(uid) for uid in _get_company_payment_method_ids(project_uuid)}
    d = dataclasses.asdict(result)
    _enrich_invoice_with_company_payment(d, result.payment_method_id, company_pm_id_strs)
    _enrich_refunds_invoice_number(d, result.refunds_invoice_id)
    _enrich_has_bank_refund(d, result.id, result.type)
    return jsonify(d)


@invoice_bp.route("/projects/<project_id>/invoices/<invoice_id>", methods=["DELETE"])
@openapi_doc(summary="Delete an invoice by ID, scoped to the project", tags=["invoices"])
@jwt_required()
@limiter.limit("20 per minute")
@require_permission("project:manage_invoices")
@require_invoice_access(write=True)
def delete_invoice(project_id: str, invoice_id: str):
    """Delete an invoice by ID, scoped to the project."""
    # Verify invoice belongs to the requested project before deleting
    try:
        existing = get_container().get_invoice_usecase.execute(UUID(invoice_id))
    except InvoiceNotFoundError:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)

    if existing.project_id != project_id:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)

    try:
        get_container().delete_invoice_usecase.execute(UUID(invoice_id))
    except AutoGeneratedInvoiceError as e:
        return _error_response("Forbidden", str(e), 403)
    except InvoiceNotFoundError:
        return _error_response("NotFound", f"Invoice {invoice_id} not found", 404)
    except ValueError as e:
        return _error_response("ValidationError", str(e), 400)

    return "", 204
