"""Update invoice use case."""

import dataclasses
from dataclasses import dataclass
from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Optional
from uuid import UUID

from app.application.invoice.dtos import InvoiceResponse
from app.application.invoice.ports import IInvoiceRepository
from app.domain.entities.invoice import (
    HIGHLIGHT_COLORS,
    Invoice,
    InvoiceType,
    MIXED_SIGN_TYPES,
    RefundableStatus,
    SettledVia,
)
from app.domain.exceptions.invoice_exceptions import (
    AppliedAmountExceedsTargetError,
    AutoGeneratedInvoiceError,
    CashAdvanceNotAllowedError,
    InvalidInvoiceDataError,
    InvoiceNotFoundError,
    RefundExceedsSourceError,
    ServiceMonthNotAllowedError,
    WorkerLinkNotAllowedError,
    WorkerNotInProjectError,
)
from app.domain.payment_methods.exceptions import PaymentMethodNotActiveError, PaymentMethodNotFoundError
from app.domain.value_objects.invoice_item import InvoiceItem

# Sentinel for "field not provided in the PATCH body".
# Distinct from None which means "explicitly set to null / clear".
_UNSET: object = object()

# Allowed settled_via string values (mirrors SettledVia enum members). Validated here
# too — not only at the Pydantic schema boundary — so any direct/internal caller of
# the use-case still gets the invariant enforced.
_VALID_SETTLED_VIA = {v.value for v in SettledVia}


@dataclass
class UpdateInvoiceRequest:
    invoice_id: UUID
    type: Optional[InvoiceType] = None
    recipient_name: Optional[str] = None
    issue_date: Optional[date] = None
    items: Optional[list] = None  # list of dicts
    recipient_address: Optional[str] = None
    notes: Optional[str] = None
    # payment_method_id uses sentinel: _UNSET = not provided, None = clear, UUID = set.
    # Callers that do not provide this field must leave it as _UNSET.
    payment_method_id: object = dataclasses.field(default_factory=lambda: _UNSET)
    # company_id is used to cross-validate that the payment method belongs to
    # the same company as the invoice's project. Optional: when None, skipped.
    company_id: Optional[UUID] = None
    # refunds_invoice_id uses sentinel: _UNSET = keep existing, None = clear link, UUID = set link.
    refunds_invoice_id: object = dataclasses.field(default_factory=lambda: _UNSET)
    # service_month uses sentinel: _UNSET = not provided, None = clear, date = set (normalized to day=1).
    service_month: object = dataclasses.field(default_factory=lambda: _UNSET)
    # settled_via uses sentinel: _UNSET = keep existing, None = clear, str = set ('cash'|'avoir').
    settled_via: object = dataclasses.field(default_factory=lambda: _UNSET)
    # applied_to_invoice_id uses sentinel: _UNSET = keep existing, None = clear link, UUID = set+validate.
    applied_to_invoice_id: object = dataclasses.field(default_factory=lambda: _UNSET)
    # worker_id uses sentinel: _UNSET = not provided, None = clear, UUID = set (validated + snapshot).
    worker_id: object = dataclasses.field(default_factory=lambda: _UNSET)
    # highlight_color uses sentinel: _UNSET = keep existing, None = clear, str = set+validate (palette).
    highlight_color: object = dataclasses.field(default_factory=lambda: _UNSET)
    # is_cash_advance uses sentinel: _UNSET = keep existing, bool = set (released_funds only).
    is_cash_advance: object = dataclasses.field(default_factory=lambda: _UNSET)


def _is_release_payment_method_only_edit(invoice: Invoice, request: UpdateInvoiceRequest) -> bool:
    """True for the narrow auto-generated carve-out: an auto-generated
    released_funds invoice whose ONLY requested change is payment_method_id
    (all other updatable fields absent/unset).

    Explicit payment_method_id=None (clearing) qualifies too — only the
    field's *presence* in the request matters, not its value. Any other
    field being provided disqualifies the carve-out and the caller must
    fall back to raising AutoGeneratedInvoiceError.
    """
    return (
        invoice.type == InvoiceType.RELEASED_FUNDS
        and request.payment_method_id is not _UNSET
        and request.type is None
        and request.recipient_name is None
        and request.issue_date is None
        and request.items is None
        and request.recipient_address is None
        and request.notes is None
        and request.refunds_invoice_id is _UNSET
        and request.service_month is _UNSET
        and request.settled_via is _UNSET
        and request.applied_to_invoice_id is _UNSET
        and request.worker_id is _UNSET
        and request.highlight_color is _UNSET
        and request.is_cash_advance is _UNSET
    )


class UpdateInvoiceUseCase:
    """Partially update an existing invoice."""

    def __init__(
        self,
        invoice_repo: IInvoiceRepository,
        payment_method_repo: object = None,  # IPaymentMethodRepository | None
        worker_reader: object = None,  # WorkerReaderPort | None
    ) -> None:
        self._repo = invoice_repo
        self._pm_repo = payment_method_repo
        self._worker_reader = worker_reader

    def execute(self, request: UpdateInvoiceRequest) -> InvoiceResponse:
        invoice = self._repo.find_by_id(request.invoice_id)
        if not invoice:
            raise InvoiceNotFoundError(f"Invoice {request.invoice_id} not found")
        if invoice.is_auto_generated and not _is_release_payment_method_only_edit(invoice, request):
            raise AutoGeneratedInvoiceError(request.invoice_id)

        # Reject any update on a fully-refunded invoice. The company already
        # reimbursed the worker; silently mutating items or amounts after the
        # fact would cause company_spent_total to diverge from the actual
        # payment. The refund status must be explicitly cleared first.
        if invoice.refundable_status == RefundableStatus.REFUNDED.value:
            raise InvalidInvoiceDataError("Refunded expenses are locked; clear the refund status first")

        updates: dict = {"updated_at": datetime.now(timezone.utc)}

        # Effective type: use requested type if provided, else fall back to existing.
        # The sign guard below uses effective_type so a PATCH that only sends items
        # (without re-sending type) still applies the correct sign rule.
        effective_type: InvoiceType = request.type if request.type is not None else invoice.type

        if request.type is not None:
            # Reject type changes on invoices that carry a refund lifecycle status.
            # Changing type would orphan the status field (only materials_services
            # supports refundable tracking) and corrupt the refund audit trail.
            if request.type != invoice.type and invoice.refundable_status is not None:
                raise InvalidInvoiceDataError("Clear refundable status before changing invoice type")
            updates["type"] = request.type

        if request.recipient_name is not None:
            name = request.recipient_name.strip()
            if not name:
                raise InvalidInvoiceDataError("Recipient name is required")
            updates["recipient_name"] = name

        if request.issue_date is not None:
            updates["issue_date"] = request.issue_date

        if request.recipient_address is not None:
            updates["recipient_address"] = request.recipient_address

        if request.notes is not None:
            updates["notes"] = request.notes

        if request.items is not None:
            if not request.items:
                raise InvalidInvoiceDataError("At least one line item is required")
            invoice_items = []
            for raw in request.items:
                qty = Decimal(str(raw.get("quantity", 0)))
                price = Decimal(str(raw.get("unit_price", 0)))
                vat = Decimal(str(raw.get("vat_rate", 0)))
                desc = str(raw.get("description", "")).strip()
                if not desc:
                    raise InvalidInvoiceDataError("Item description is required")
                if qty <= 0:
                    raise InvalidInvoiceDataError("Item quantity must be greater than 0")
                # Mixed-sign price allowed only for materials_services + refund.
                # Use effective_type so a PATCH without resending type still enforces the correct rule.
                if price < 0 and effective_type not in MIXED_SIGN_TYPES:
                    raise InvalidInvoiceDataError(
                        f"Item unit_price cannot be negative for invoice type '{effective_type.value}'"
                    )
                invoice_items.append(InvoiceItem(description=desc, quantity=qty, unit_price=price, vat_rate=vat))
            updates["items"] = invoice_items

        # Payment method: only process if the key was explicitly provided.
        if request.payment_method_id is not _UNSET:
            pm_id = request.payment_method_id  # None or UUID

            if pm_id is None:
                # Explicit null → clear both columns
                updates["payment_method_id"] = None
                updates["payment_method_label"] = None
            else:
                # UUID provided → validate and snapshot label
                if self._pm_repo is None:
                    raise InvalidInvoiceDataError("Payment method support is not available")

                method = self._pm_repo.find_by_id_for_update(pm_id)
                if method is None:
                    raise PaymentMethodNotFoundError(pm_id)
                if not method.is_active:
                    raise PaymentMethodNotActiveError(pm_id)
                # Cross-company guard
                if request.company_id is not None and method.company_id != request.company_id:
                    from app.domain.companies.exceptions import ForbiddenCompanyError

                    raise ForbiddenCompanyError(invoice.created_by, request.company_id)

                updates["payment_method_id"] = method.id
                updates["payment_method_label"] = method.label

        # service_month sentinel: absent = keep existing (unless cleared below), None = clear,
        # date = set (normalized to day=1, only valid when effective_type is labor).
        if request.service_month is not _UNSET:
            if request.service_month is None:
                updates["service_month"] = None
            else:
                if effective_type != InvoiceType.LABOR:
                    raise ServiceMonthNotAllowedError("service_month may only be set on invoices of type 'labor'")
                updates["service_month"] = request.service_month.replace(day=1)
        elif effective_type != InvoiceType.LABOR and invoice.service_month is not None:
            # Type is changing away from labor (or already isn't labor) while a
            # service_month is still stored and the PATCH didn't touch it — clear
            # it server-side so no non-labor invoice ever carries a stale month.
            updates["service_month"] = None

        # worker_id sentinel: absent = keep existing (unless cleared below), None = clear,
        # UUID = set+validate (only valid when effective_type is labor). When set, the
        # resolved worker display name overrides recipient_name in this same PATCH
        # (server-side snapshot, not just a default).
        if request.worker_id is not _UNSET:
            if request.worker_id is None:
                updates["worker_id"] = None
            else:
                if effective_type != InvoiceType.LABOR:
                    raise WorkerLinkNotAllowedError("worker_id may only be set on invoices of type 'labor'")
                if self._worker_reader is None:
                    raise InvalidInvoiceDataError("Worker link support is not available")
                worker = self._worker_reader.get_for_project(request.worker_id, invoice.project_id)
                if worker is None:
                    raise WorkerNotInProjectError(f"Worker {request.worker_id} not found in this project")
                updates["worker_id"] = worker.id
                updates["recipient_name"] = worker.display_name
        elif effective_type != InvoiceType.LABOR and invoice.worker_id is not None:
            # Type is changing away from labor (or already isn't labor) while a
            # worker link is still stored and the PATCH didn't touch it — clear it
            # server-side so no non-labor invoice ever carries a stale worker link.
            updates["worker_id"] = None

        # refunds_invoice_id sentinel: absent = keep existing, None = clear, UUID = set+validate.
        if request.refunds_invoice_id is not _UNSET:
            link_id = request.refunds_invoice_id  # None or UUID
            if link_id is None:
                # Explicit null → clear the link
                updates["refunds_invoice_id"] = None
            else:
                # UUID provided → validate link target + cap
                if effective_type != InvoiceType.RETURN:
                    raise InvalidInvoiceDataError("refunds_invoice_id may only be set on invoices of type 'refund'")
                link_uuid: UUID = link_id  # type: ignore[assignment]
                if link_uuid == invoice.id:
                    raise InvalidInvoiceDataError("An invoice cannot refund itself")
                source = self._repo.find_by_id(link_uuid)
                if source is None:
                    raise InvalidInvoiceDataError(f"Source invoice {link_uuid} not found")
                if source.project_id != invoice.project_id:
                    raise InvalidInvoiceDataError("refunds_invoice_id must reference an invoice in the same project")
                if source.type != InvoiceType.MATERIALS_SERVICES:
                    raise InvalidInvoiceDataError("refunds_invoice_id must reference a materials_services invoice")
                # Cap: exclude this invoice's own row from the Σ (avoid self-double-counting on update).
                new_items = updates.get("items", invoice.items)
                this_total = sum((item.total for item in new_items), Decimal("0"))
                existing_refunds = self._repo.sum_refunds_for_source(source.id, exclude_invoice_id=invoice.id)
                remaining = source.total_amount + existing_refunds
                if remaining + this_total < 0:
                    raise RefundExceedsSourceError(
                        f"Refund exceeds source invoice amount. Remaining refundable: {remaining:.2f}"
                    )
                updates["refunds_invoice_id"] = link_uuid
        elif effective_type != InvoiceType.RETURN and invoice.refunds_invoice_id is not None:
            # Type is changing away from 'return' (or already isn't) while a
            # refunds_invoice_id link is still stored and the PATCH didn't touch it —
            # clear it server-side, mirroring the service_month auto-clear above, so no
            # non-return invoice ever carries a stale refund-source link.
            updates["refunds_invoice_id"] = None
        elif effective_type == InvoiceType.RETURN and invoice.refunds_invoice_id is not None:
            # Link was not touched in this PATCH but the invoice already has one.
            # Re-validate the cap in case the item amounts changed.
            if "items" in updates:
                source = self._repo.find_by_id(invoice.refunds_invoice_id)
                if source is not None:
                    new_items = updates["items"]
                    this_total = sum((item.total for item in new_items), Decimal("0"))
                    existing_refunds = self._repo.sum_refunds_for_source(source.id, exclude_invoice_id=invoice.id)
                    remaining = source.total_amount + existing_refunds
                    if remaining + this_total < 0:
                        raise RefundExceedsSourceError(
                            f"Refund exceeds source invoice amount. Remaining refundable: {remaining:.2f}"
                        )

        # settled_via sentinel: absent = keep existing, None = clear, str = set+validate.
        if request.settled_via is not _UNSET:
            if request.settled_via is None:
                updates["settled_via"] = None
            else:
                if effective_type != InvoiceType.RETURN:
                    raise InvalidInvoiceDataError("settled_via may only be set on invoices of type 'return'")
                if request.settled_via not in _VALID_SETTLED_VIA:
                    raise InvalidInvoiceDataError(
                        f"settled_via must be one of: {', '.join(sorted(_VALID_SETTLED_VIA))}"
                    )
                updates["settled_via"] = request.settled_via
        elif effective_type != InvoiceType.RETURN and invoice.settled_via is not None:
            # Type is changing away from 'return' (or already isn't) while settled_via
            # is still stored and the PATCH didn't touch it — clear it server-side,
            # mirroring the service_month auto-clear above, so no non-return invoice
            # ever carries a stale settlement mode.
            updates["settled_via"] = None

        effective_settled_via = updates["settled_via"] if "settled_via" in updates else invoice.settled_via

        # applied_to_invoice_id sentinel: absent = keep existing, None = clear, UUID = set+validate.
        if request.applied_to_invoice_id is not _UNSET:
            applied_link_id = request.applied_to_invoice_id  # None or UUID
            if applied_link_id is None:
                # Explicit null → clear the link. Method is deliberately left untouched.
                updates["applied_to_invoice_id"] = None
            else:
                if effective_type != InvoiceType.RETURN:
                    raise InvalidInvoiceDataError("applied_to_invoice_id may only be set on invoices of type 'return'")
                if effective_settled_via != SettledVia.AVOIR.value:
                    raise InvalidInvoiceDataError("applied_to_invoice_id may only be set when settled_via is 'avoir'")
                applied_link_uuid: UUID = applied_link_id  # type: ignore[assignment]
                if applied_link_uuid == invoice.id:
                    raise InvalidInvoiceDataError("An invoice cannot be applied to itself")
                target = self._repo.find_by_id(applied_link_uuid)
                if target is None:
                    raise InvalidInvoiceDataError(f"Target invoice {applied_link_uuid} not found")
                if target.project_id != invoice.project_id:
                    raise InvalidInvoiceDataError("applied_to_invoice_id must reference an invoice in the same project")
                if target.type in (InvoiceType.RETURN, InvoiceType.RELEASED_FUNDS):
                    raise InvalidInvoiceDataError(
                        "applied_to_invoice_id must reference an invoice that is not a return or released_funds"
                    )
                # Cap: exclude this invoice's own row from the Σ (avoid self-double-counting on update).
                # Race (accepted, not locked): this is a read-then-write check with no
                # row/advisory lock, so two concurrent updates against the same target
                # could both pass and jointly exceed the cap — identical, accepted class
                # of drift as the pre-existing sum_refunds_for_source cap check above.
                new_items = updates.get("items", invoice.items)
                this_total = sum((item.total for item in new_items), Decimal("0"))
                existing_applied = self._repo.sum_applied_for_target(target.id, exclude_invoice_id=invoice.id)
                total_applied = existing_applied + this_total
                if abs(total_applied) > target.total_amount:
                    remaining = target.total_amount - abs(existing_applied)
                    raise AppliedAmountExceedsTargetError(
                        f"Applied amount exceeds target invoice total. Remaining applicable: {remaining:.2f}"
                    )
                updates["applied_to_invoice_id"] = target.id
                # Auto-align: server-side copy of the target's payment method, even when
                # NULL — mirrors the create-time behaviour exactly.
                updates["payment_method_id"] = target.payment_method_id
                updates["payment_method_label"] = target.payment_method_label
        elif effective_type != InvoiceType.RETURN and invoice.applied_to_invoice_id is not None:
            # Type is changing away from 'return' (or already isn't) while
            # applied_to_invoice_id is still stored and the PATCH didn't touch it —
            # clear it server-side, mirroring the service_month auto-clear above, so
            # the target's cap is freed and no non-return invoice ever carries a stale
            # avoir-application link.
            updates["applied_to_invoice_id"] = None
        elif effective_type == InvoiceType.RETURN and invoice.applied_to_invoice_id is not None:
            # Link was not touched in this PATCH but the invoice already has one.
            # Re-validate when items changed (cap) or settled_via changed away from
            # 'avoir' (the link would no longer be valid on its own — the caller must
            # explicitly clear applied_to_invoice_id in the same PATCH).
            if effective_settled_via != SettledVia.AVOIR.value:
                raise InvalidInvoiceDataError(
                    "applied_to_invoice_id requires settled_via='avoir'; clear the link before changing settled_via"
                )
            if "items" in updates:
                target = self._repo.find_by_id(invoice.applied_to_invoice_id)
                if target is not None:
                    new_items = updates["items"]
                    this_total = sum((item.total for item in new_items), Decimal("0"))
                    existing_applied = self._repo.sum_applied_for_target(target.id, exclude_invoice_id=invoice.id)
                    total_applied = existing_applied + this_total
                    if abs(total_applied) > target.total_amount:
                        remaining = target.total_amount - abs(existing_applied)
                        raise AppliedAmountExceedsTargetError(
                            f"Applied amount exceeds target invoice total. Remaining applicable: {remaining:.2f}"
                        )

        # highlight_color sentinel: absent = keep existing, None = clear, str = set+validate.
        # Applies to invoices of every type — a purely visual annotation, no type gating.
        if request.highlight_color is not _UNSET:
            if request.highlight_color is None:
                updates["highlight_color"] = None
            else:
                if request.highlight_color not in HIGHLIGHT_COLORS:
                    raise InvalidInvoiceDataError(
                        f"highlight_color must be one of: {', '.join(sorted(HIGHLIGHT_COLORS))}"
                    )
                updates["highlight_color"] = request.highlight_color

        # is_cash_advance sentinel: absent = keep existing (unless cleared below), bool = set.
        # Only a released_funds row may carry the flag (it is meaningless — and
        # misleading in the UI — on an expense row); a type change away from
        # released_funds clears it server-side so no stale flag survives.
        if request.is_cash_advance is not _UNSET:
            if request.is_cash_advance and effective_type != InvoiceType.RELEASED_FUNDS:
                raise CashAdvanceNotAllowedError("is_cash_advance may only be set on invoices of type 'released_funds'")
            updates["is_cash_advance"] = bool(request.is_cash_advance)
        elif effective_type != InvoiceType.RELEASED_FUNDS and invoice.is_cash_advance:
            updates["is_cash_advance"] = False

        updated = dataclasses.replace(invoice, **updates)
        saved = self._repo.update(updated)
        return InvoiceResponse.from_entity(saved)
