"""Update invoice use case."""

import dataclasses
from dataclasses import dataclass
from datetime import date, datetime, timezone
from decimal import Decimal
from typing import Optional
from uuid import UUID

from app.application.invoice.dtos import InvoiceResponse
from app.application.invoice.ports import IInvoiceRepository
from app.application.tags.exceptions import InvalidProjectTagError
from app.domain.entities.invoice import InvoiceType, RefundableStatus, MIXED_SIGN_TYPES
from app.domain.exceptions.invoice_exceptions import (
    AutoGeneratedInvoiceError,
    InvalidInvoiceDataError,
    InvoiceNotFoundError,
    RefundExceedsSourceError,
    ServiceMonthNotAllowedError,
)
from app.domain.payment_methods.exceptions import PaymentMethodNotActiveError, PaymentMethodNotFoundError
from app.domain.value_objects.invoice_item import InvoiceItem

# Sentinel for "field not provided in the PATCH body".
# Distinct from None which means "explicitly set to null / clear".
_UNSET: object = object()


@dataclass
class UpdateInvoiceRequest:
    invoice_id: UUID
    type: Optional[InvoiceType] = None
    recipient_name: Optional[str] = None
    issue_date: Optional[date] = None
    items: Optional[list] = None  # list of dicts
    recipient_address: Optional[str] = None
    notes: Optional[str] = None
    # payment_method_id uses sentinel: _UNSET = not provided, None = clear, UUID = set.
    # Callers that do not provide this field must leave it as _UNSET.
    payment_method_id: object = dataclasses.field(default_factory=lambda: _UNSET)
    # company_id is used to cross-validate that the payment method belongs to
    # the same company as the invoice's project. Optional: when None, skipped.
    company_id: Optional[UUID] = None
    # tag_id uses sentinel: _UNSET = not provided, None = clear tag, UUID = assign tag.
    tag_id: object = dataclasses.field(default_factory=lambda: _UNSET)
    # refunds_invoice_id uses sentinel: _UNSET = keep existing, None = clear link, UUID = set link.
    refunds_invoice_id: object = dataclasses.field(default_factory=lambda: _UNSET)
    # service_month uses sentinel: _UNSET = not provided, None = clear, date = set (normalized to day=1).
    service_month: object = dataclasses.field(default_factory=lambda: _UNSET)


class UpdateInvoiceUseCase:
    """Partially update an existing invoice."""

    def __init__(
        self,
        invoice_repo: IInvoiceRepository,
        payment_method_repo: object = None,  # IPaymentMethodRepository | None
        tag_repo=None,  # ProjectTagRepositoryPort | None
    ) -> None:
        self._repo = invoice_repo
        self._pm_repo = payment_method_repo
        self._tag_repo = tag_repo

    def execute(self, request: UpdateInvoiceRequest) -> InvoiceResponse:
        invoice = self._repo.find_by_id(request.invoice_id)
        if not invoice:
            raise InvoiceNotFoundError(f"Invoice {request.invoice_id} not found")
        if invoice.is_auto_generated:
            raise AutoGeneratedInvoiceError(request.invoice_id)

        # Reject any update on a fully-refunded invoice. The company already
        # reimbursed the worker; silently mutating items or amounts after the
        # fact would cause company_spent_total to diverge from the actual
        # payment. The refund status must be explicitly cleared first.
        if invoice.refundable_status == RefundableStatus.REFUNDED.value:
            raise InvalidInvoiceDataError("Refunded expenses are locked; clear the refund status first")

        updates: dict = {"updated_at": datetime.now(timezone.utc)}

        # Effective type: use requested type if provided, else fall back to existing.
        # The sign guard below uses effective_type so a PATCH that only sends items
        # (without re-sending type) still applies the correct sign rule.
        effective_type: InvoiceType = request.type if request.type is not None else invoice.type

        if request.type is not None:
            # Reject type changes on invoices that carry a refund lifecycle status.
            # Changing type would orphan the status field (only materials_services
            # supports refundable tracking) and corrupt the refund audit trail.
            if request.type != invoice.type and invoice.refundable_status is not None:
                raise InvalidInvoiceDataError("Clear refundable status before changing invoice type")
            updates["type"] = request.type

        if request.recipient_name is not None:
            name = request.recipient_name.strip()
            if not name:
                raise InvalidInvoiceDataError("Recipient name is required")
            updates["recipient_name"] = name

        if request.issue_date is not None:
            updates["issue_date"] = request.issue_date

        if request.recipient_address is not None:
            updates["recipient_address"] = request.recipient_address

        if request.notes is not None:
            updates["notes"] = request.notes

        if request.items is not None:
            if not request.items:
                raise InvalidInvoiceDataError("At least one line item is required")
            invoice_items = []
            for raw in request.items:
                qty = Decimal(str(raw.get("quantity", 0)))
                price = Decimal(str(raw.get("unit_price", 0)))
                vat = Decimal(str(raw.get("vat_rate", 0)))
                desc = str(raw.get("description", "")).strip()
                if not desc:
                    raise InvalidInvoiceDataError("Item description is required")
                if qty <= 0:
                    raise InvalidInvoiceDataError("Item quantity must be greater than 0")
                # Mixed-sign price allowed only for materials_services + refund.
                # Use effective_type so a PATCH without resending type still enforces the correct rule.
                if price < 0 and effective_type not in MIXED_SIGN_TYPES:
                    raise InvalidInvoiceDataError(
                        f"Item unit_price cannot be negative for invoice type '{effective_type.value}'"
                    )
                invoice_items.append(InvoiceItem(description=desc, quantity=qty, unit_price=price, vat_rate=vat))
            updates["items"] = invoice_items

        # Payment method: only process if the key was explicitly provided.
        if request.payment_method_id is not _UNSET:
            pm_id = request.payment_method_id  # None or UUID

            if pm_id is None:
                # Explicit null → clear both columns
                updates["payment_method_id"] = None
                updates["payment_method_label"] = None
            else:
                # UUID provided → validate and snapshot label
                if self._pm_repo is None:
                    raise InvalidInvoiceDataError("Payment method support is not available")

                method = self._pm_repo.find_by_id_for_update(pm_id)
                if method is None:
                    raise PaymentMethodNotFoundError(pm_id)
                if not method.is_active:
                    raise PaymentMethodNotActiveError(pm_id)
                # Cross-company guard
                if request.company_id is not None and method.company_id != request.company_id:
                    from app.domain.companies.exceptions import ForbiddenCompanyError

                    raise ForbiddenCompanyError(invoice.created_by, request.company_id)

                updates["payment_method_id"] = method.id
                updates["payment_method_label"] = method.label

        # tag_id: only process if explicitly provided (not _UNSET).
        if request.tag_id is not _UNSET:
            # Guard: when assigning a tag (not clearing), it must belong to this project.
            if request.tag_id is not None and self._tag_repo is not None:
                tag_uuid: UUID = request.tag_id  # type: ignore[assignment]
                tag = self._tag_repo.get_by_id(tag_uuid)
                if tag is None or tag.project_id != invoice.project_id:
                    raise InvalidProjectTagError(f"Tag {request.tag_id} does not belong to this project")
            updates["tag_id"] = request.tag_id  # None = clear, UUID = assign

        # service_month sentinel: absent = keep existing (unless cleared below), None = clear,
        # date = set (normalized to day=1, only valid when effective_type is labor).
        if request.service_month is not _UNSET:
            if request.service_month is None:
                updates["service_month"] = None
            else:
                if effective_type != InvoiceType.LABOR:
                    raise ServiceMonthNotAllowedError("service_month may only be set on invoices of type 'labor'")
                updates["service_month"] = request.service_month.replace(day=1)
        elif effective_type != InvoiceType.LABOR and invoice.service_month is not None:
            # Type is changing away from labor (or already isn't labor) while a
            # service_month is still stored and the PATCH didn't touch it — clear
            # it server-side so no non-labor invoice ever carries a stale month.
            updates["service_month"] = None

        # refunds_invoice_id sentinel: absent = keep existing, None = clear, UUID = set+validate.
        if request.refunds_invoice_id is not _UNSET:
            link_id = request.refunds_invoice_id  # None or UUID
            if link_id is None:
                # Explicit null → clear the link
                updates["refunds_invoice_id"] = None
            else:
                # UUID provided → validate link target + cap
                if effective_type != InvoiceType.REFUND:
                    raise InvalidInvoiceDataError("refunds_invoice_id may only be set on invoices of type 'refund'")
                link_uuid: UUID = link_id  # type: ignore[assignment]
                if link_uuid == invoice.id:
                    raise InvalidInvoiceDataError("An invoice cannot refund itself")
                source = self._repo.find_by_id(link_uuid)
                if source is None:
                    raise InvalidInvoiceDataError(f"Source invoice {link_uuid} not found")
                if source.project_id != invoice.project_id:
                    raise InvalidInvoiceDataError("refunds_invoice_id must reference an invoice in the same project")
                if source.type != InvoiceType.MATERIALS_SERVICES:
                    raise InvalidInvoiceDataError("refunds_invoice_id must reference a materials_services invoice")
                # Cap: exclude this invoice's own row from the Σ (avoid self-double-counting on update).
                new_items = updates.get("items", invoice.items)
                this_total = sum((item.total for item in new_items), Decimal("0"))
                existing_refunds = self._repo.sum_refunds_for_source(source.id, exclude_invoice_id=invoice.id)
                remaining = source.total_amount + existing_refunds
                if remaining + this_total < 0:
                    raise RefundExceedsSourceError(
                        f"Refund exceeds source invoice amount. Remaining refundable: {remaining:.2f}"
                    )
                updates["refunds_invoice_id"] = link_uuid
        elif effective_type == InvoiceType.REFUND and invoice.refunds_invoice_id is not None:
            # Link was not touched in this PATCH but the invoice already has one.
            # Re-validate the cap in case the item amounts changed.
            if "items" in updates:
                source = self._repo.find_by_id(invoice.refunds_invoice_id)
                if source is not None:
                    new_items = updates["items"]
                    this_total = sum((item.total for item in new_items), Decimal("0"))
                    existing_refunds = self._repo.sum_refunds_for_source(source.id, exclude_invoice_id=invoice.id)
                    remaining = source.total_amount + existing_refunds
                    if remaining + this_total < 0:
                        raise RefundExceedsSourceError(
                            f"Refund exceeds source invoice amount. Remaining refundable: {remaining:.2f}"
                        )

        updated = dataclasses.replace(invoice, **updates)
        saved = self._repo.update(updated)
        return InvoiceResponse.from_entity(saved)
