"""Localised labels for the expense (invoice) export — en, fr and vi.

English stays the default so a request without a locale renders exactly as
before. Every locale carries the same keys (a unit test checks the parity).
"""

from __future__ import annotations

SUPPORTED_LOCALES = ("en", "fr", "vi")
DEFAULT_LOCALE = "en"

_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "export_title": "INVOICE EXPORT",
        "range": "Range: {start} to {end}",
        "generated": "Generated {at} by {email}",
        "footer": "Generated by {email} · {at}",
        "page": "Page {n}",
        "summary_sheet": "Summary",
        "no_invoices": "No invoices in range {start} to {end}",
        "total_invoices": "Total invoices",
        "total_expenses": "Total expenses",
        "released_funds": "Released funds",
        "from": "From",
        "to": "To",
        "from_month": "From month",
        "to_month": "To month",
        "subtotals_by_type": "Subtotals by type",
        "invoices": "Invoices",
        "col_date": "Date",
        "col_type": "Type",
        "col_recipient": "Recipient",
        "col_items": "Items",
        "col_total": "Total",
        "col_count": "Count",
        "col_invoice_count": "Invoice count",
        "col_payment_month": "Payment month",
        "grand_total_row": "TOTAL EXPENSES",
        "total_row": "TOTAL",
        "type_sheet": "{type} invoices",
        "type_title": "{type} invoices — {project}",
        "invoice": "INVOICE",
        "invoice_no": "Invoice #",
        "issue_date": "Issue date",
        "description": "Description",
        "qty": "Qty",
        "unit_price": "Unit price",
        "notes": "Notes",
        "cash_advance": "cash advance",
    },
    "fr": {
        "export_title": "EXPORT DES DÉPENSES",
        "range": "Période : {start} à {end}",
        "generated": "Généré le {at} par {email}",
        "footer": "Généré par {email} · {at}",
        "page": "Page {n}",
        "summary_sheet": "Synthèse",
        "no_invoices": "Aucune facture entre {start} et {end}",
        "total_invoices": "Nombre de factures",
        "total_expenses": "Total des dépenses",
        "released_funds": "Fonds débloqués",
        "from": "Du",
        "to": "Au",
        "from_month": "Mois de début",
        "to_month": "Mois de fin",
        "subtotals_by_type": "Sous-totaux par type",
        "invoices": "Factures",
        "col_date": "Date",
        "col_type": "Type",
        "col_recipient": "Destinataire",
        "col_items": "Lignes",
        "col_total": "Total",
        "col_count": "Nombre",
        "col_invoice_count": "Nombre de factures",
        "col_payment_month": "Mois de paie",
        "grand_total_row": "TOTAL DES DÉPENSES",
        "total_row": "TOTAL",
        "type_sheet": "{type}",
        "type_title": "{type} — {project}",
        "invoice": "FACTURE",
        "invoice_no": "N° de facture",
        "issue_date": "Date d'émission",
        "description": "Description",
        "qty": "Qté",
        "unit_price": "Prix unitaire",
        "notes": "Notes",
        "cash_advance": "avance de trésorerie",
    },
    "vi": {
        "export_title": "XUẤT CHI PHÍ",
        "range": "Khoảng thời gian: {start} đến {end}",
        "generated": "Tạo lúc {at} bởi {email}",
        "footer": "Tạo bởi {email} · {at}",
        "page": "Trang {n}",
        "summary_sheet": "Tổng hợp",
        "no_invoices": "Không có hóa đơn từ {start} đến {end}",
        "total_invoices": "Tổng số hóa đơn",
        "total_expenses": "Tổng chi phí",
        "released_funds": "Tiền đã giải ngân",
        "from": "Từ",
        "to": "Đến",
        "from_month": "Từ tháng",
        "to_month": "Đến tháng",
        "subtotals_by_type": "Tổng theo loại",
        "invoices": "Hóa đơn",
        "col_date": "Ngày",
        "col_type": "Loại",
        "col_recipient": "Người nhận",
        "col_items": "Số dòng",
        "col_total": "Tổng",
        "col_count": "Số lượng",
        "col_invoice_count": "Số hóa đơn",
        "col_payment_month": "Tháng lương",
        "grand_total_row": "TỔNG CHI PHÍ",
        "total_row": "TỔNG",
        "type_sheet": "{type}",
        "type_title": "{type} — {project}",
        "invoice": "HÓA ĐƠN",
        "invoice_no": "Số hóa đơn",
        "issue_date": "Ngày lập",
        "description": "Mô tả",
        "qty": "SL",
        "unit_price": "Đơn giá",
        "notes": "Ghi chú",
        "cash_advance": "tạm ứng",
    },
}

_TYPE_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "released_funds": "Released Funds",
        "labor": "Labor",
        "materials_services": "Materials & Services",
        "others": "Others",
        "return": "Return",
    },
    "fr": {
        "released_funds": "Fonds débloqués",
        "labor": "Main-d'œuvre",
        "materials_services": "Matériaux et services",
        "others": "Autres",
        "return": "Retour",
    },
    "vi": {
        "released_funds": "Tiền giải ngân",
        "labor": "Nhân công",
        "materials_services": "Vật tư & dịch vụ",
        "others": "Khác",
        "return": "Trả hàng",
    },
}


def normalize_locale(locale: str | None) -> str:
    """Return a supported locale, falling back to English."""
    return locale if locale in SUPPORTED_LOCALES else DEFAULT_LOCALE


def t(locale: str, key: str, **kwargs: object) -> str:
    """Label `key` in `locale` (English fallback), formatted with `kwargs`."""
    text = _LABELS[normalize_locale(locale)].get(key) or _LABELS[DEFAULT_LOCALE][key]
    return text.format(**kwargs) if kwargs else text


def type_label(type_value: str, locale: str = DEFAULT_LOCALE) -> str:
    """Display name of an invoice type."""
    labels = _TYPE_LABELS[normalize_locale(locale)]
    return labels.get(type_value, type_value.replace("_", " ").title())


def type_labels(locale: str = DEFAULT_LOCALE) -> dict[str, str]:
    """Every invoice type's display name in `locale`."""
    return dict(_TYPE_LABELS[normalize_locale(locale)])
