"""Pure-python PDF builder for invoice export.

build_pdf(context: InvoiceExportContext, bundle: InvoiceBundle) -> bytes

Layout (A4 portrait, 15mm margins)
------------------------------------
Page 1 — Summary:
  1. Header band — project name (24pt bold) + "INVOICE EXPORT" subtitle
  2. Meta line — range, generated datetime, generated_by email (9pt grey)
  3. KPI strip (4 cells) — Total invoices | Grand total | From | To
  4. "Subtotals by type" heading + table (Type | Count | Total)
  5. "Invoices" heading + table (# | Date | Type | Recipient | Total)

Pages 2..N+1 — one polished invoice per page:
  1. Header band: project name (left) + "INVOICE" (right) + bottom hairline
  2. Meta block (2-col table): Invoice # / Type / Issue date / Recipient (+ address)
  3. Items table: Description | Qty | Unit price | Total (zebra #fafafa rows)
  4. Grand-total band: full-width bold row, light grey background, top border
  5. Notes section (only if notes non-empty)

Page footer (every page):
  Left:  "Generated by <email> · <ISO datetime>"
  Right: "Page X"

Empty range: page 1 only, paragraph "No invoices in range … to …" replaces KPI/tables.

Currency rule (LOCKED)
-----------------------
All monetary values formatted via format_eur_fr(Decimal) → "200,00 €"
(matches xlsx number_format + FE Intl.NumberFormat fr-FR).

Font reuse note
---------------
This module deliberately reuses fonts from app.domain.labor.export.fonts via
the cross-package path below. This avoids duplicating ~1.5 MB of TTF binaries.
Accepted trade-off: if the labor package moves, update _FONTS_DIR here.
  _FONTS_DIR = Path(__file__).resolve().parent.parent.parent / "labor" / "export" / "fonts"

XML escaping
------------
All user-supplied strings (project name, recipient name/address, notes, item
descriptions) are passed through xml.sax.saxutils.escape before being rendered
in ReportLab Paragraph objects. Mirrors the labor PDF builder pattern.
"""

from __future__ import annotations

from io import BytesIO
from pathlib import Path
from typing import List
from xml.sax.saxutils import escape as _xml_escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.domain.labor.export.format import format_eur_fr
from app.domain.invoice.export.format import TYPE_LABEL_EN
from app.domain.invoice.export.models import InvoiceBundle, InvoiceExportContext
from app.domain.entities.invoice import Invoice

# ---------------------------------------------------------------------------
# Cross-package font reuse (see module docstring)
# ---------------------------------------------------------------------------

_FONTS_DIR = Path(__file__).resolve().parent.parent.parent / "labor" / "export" / "fonts"

# ---------------------------------------------------------------------------
# Font registration — executed at module import time
# ---------------------------------------------------------------------------
# Running at import eliminates the lazy-flag race condition where two concurrent
# requests could both observe _FONT_REGISTERED==False and double-register.
# Module-level code is serialised by the Python import system.
# A try/except guards against missing font files so import never hard-crashes;
# build_pdf() will fail (via ReportLab) if fonts are truly absent, surfacing
# the error at the right call site with a clear traceback.

try:
    pdfmetrics.registerFont(TTFont("DejaVu", str(_FONTS_DIR / "DejaVuSans.ttf")))
    pdfmetrics.registerFont(TTFont("DejaVu-Bold", str(_FONTS_DIR / "DejaVuSans-Bold.ttf")))
    pdfmetrics.registerFontFamily(
        "DejaVu",
        normal="DejaVu",
        bold="DejaVu-Bold",
        italic="DejaVu",
        boldItalic="DejaVu-Bold",
    )
except Exception as _font_err:  # noqa: BLE001
    import warnings

    warnings.warn(
        f"invoice pdf_builder: DejaVu font registration failed ({_font_err}). "
        "PDF generation will fail if fonts are unavailable.",
        stacklevel=1,
    )


# ---------------------------------------------------------------------------
# Stylesheet
# ---------------------------------------------------------------------------


def _make_styles() -> dict:
    """Return ParagraphStyle objects keyed by logical name (all DejaVu, never Helvetica)."""
    title = ParagraphStyle(
        "title",
        fontName="DejaVu-Bold",
        fontSize=24,
        leading=28,
        spaceAfter=2,
    )
    subtitle = ParagraphStyle(
        "subtitle",
        fontName="DejaVu",
        fontSize=11,
        leading=14,
        spaceAfter=4,
        textColor=colors.HexColor("#444444"),
    )
    meta = ParagraphStyle(
        "meta",
        fontName="DejaVu",
        fontSize=9,
        leading=12,
        textColor=colors.grey,
        spaceAfter=2,
    )
    section_heading = ParagraphStyle(
        "section_heading",
        fontName="DejaVu-Bold",
        fontSize=11,
        leading=14,
        spaceBefore=6,
        spaceAfter=2,
    )
    body = ParagraphStyle(
        "body",
        fontName="DejaVu",
        fontSize=9,
        leading=12,
    )
    body_italic = ParagraphStyle(
        "body_italic",
        fontName="DejaVu",
        fontSize=11,
        leading=14,
        textColor=colors.grey,
    )
    kpi_label = ParagraphStyle(
        "kpi_label",
        fontName="DejaVu",
        fontSize=7,
        leading=9,
        textColor=colors.grey,
        alignment=1,
    )
    kpi_value = ParagraphStyle(
        "kpi_value",
        fontName="DejaVu-Bold",
        fontSize=10,
        leading=13,
        alignment=1,
    )
    inv_header_left = ParagraphStyle(
        "inv_header_left",
        fontName="DejaVu-Bold",
        fontSize=13,
        leading=16,
    )
    inv_header_right = ParagraphStyle(
        "inv_header_right",
        fontName="DejaVu-Bold",
        fontSize=13,
        leading=16,
        alignment=2,
    )
    footer_style = ParagraphStyle(
        "footer_style",
        fontName="DejaVu",
        fontSize=8,
        leading=10,
    )
    return {
        "title": title,
        "subtitle": subtitle,
        "meta": meta,
        "section_heading": section_heading,
        "body": body,
        "body_italic": body_italic,
        "kpi_label": kpi_label,
        "kpi_value": kpi_value,
        "inv_header_left": inv_header_left,
        "inv_header_right": inv_header_right,
        "footer": footer_style,
    }


# ---------------------------------------------------------------------------
# Invoice sort key
# ---------------------------------------------------------------------------


def _invoice_sort_key(inv: Invoice):
    return (inv.issue_date, inv.type.value, inv.invoice_number)


# ---------------------------------------------------------------------------
# Page footer callback
# ---------------------------------------------------------------------------


def _make_footer_callback(context: InvoiceExportContext):
    """Return a canvas callback that draws footer on every page.

    Left:  "Generated by <email> · <ISO datetime>"
    Right: "Page X"
    (Page X only — two-pass X/Y total count is future work; mirrors labor precedent.)
    """
    iso_dt = context.generated_at.strftime("%Y-%m-%dT%H:%M")
    left_text = f"Generated by {context.generated_by_email} · {iso_dt}"

    def _footer(canvas, doc) -> None:  # type: ignore[no-untyped-def]
        canvas.saveState()
        canvas.setFont("DejaVu", 8)
        y = 8 * mm
        canvas.drawString(15 * mm, y, left_text)
        canvas.drawRightString(A4[0] - 15 * mm, y, f"Page {doc.page}")
        canvas.restoreState()

    return _footer


# ---------------------------------------------------------------------------
# Summary page elements
# ---------------------------------------------------------------------------


def _render_summary_header(context: InvoiceExportContext, styles: dict) -> list:
    """Project name (24pt bold) + 'INVOICE EXPORT' subtitle + meta line."""
    from_label = context.range.from_month.strftime("%Y-%m")
    to_label = context.range.to_month.strftime("%Y-%m")
    meta_text = (
        f"Range: {from_label} to {to_label}"
        f" · Generated {context.generated_at.strftime('%Y-%m-%d %H:%M')}"
        f" by {_xml_escape(context.generated_by_email)}"
    )
    return [
        Paragraph(_xml_escape(context.project_name), styles["title"]),
        Paragraph("INVOICE EXPORT", styles["subtitle"]),
        Paragraph(meta_text, styles["meta"]),
    ]


def _render_kpi_strip(bundle: InvoiceBundle, context: InvoiceExportContext, styles: dict) -> list:
    """4-cell KPI strip: Total invoices | Grand total | From | To."""
    from_label = context.range.from_month.strftime("%Y-%m")
    to_label = context.range.to_month.strftime("%Y-%m")

    kpi_data = [
        [
            Paragraph("Total invoices", styles["kpi_label"]),
            Paragraph("Grand total", styles["kpi_label"]),
            Paragraph("From", styles["kpi_label"]),
            Paragraph("To", styles["kpi_label"]),
        ],
        [
            Paragraph(str(bundle.invoice_count), styles["kpi_value"]),
            Paragraph(format_eur_fr(bundle.grand_total), styles["kpi_value"]),
            Paragraph(from_label, styles["kpi_value"]),
            Paragraph(to_label, styles["kpi_value"]),
        ],
    ]

    table = Table(kpi_data, colWidths="*")
    table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F0F4FA")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )
    return [table]


def _render_subtotals_table(bundle: InvoiceBundle, styles: dict, usable_width: float) -> list:
    """'Subtotals by type' heading + table (Type | Count | Total)."""
    col_widths = [usable_width * 0.4, usable_width * 0.2, usable_width * 0.4]

    header_row = ["Type", "Count", "Total"]
    table_data = [header_row]
    for sub in bundle.subtotals_by_type:
        type_label = TYPE_LABEL_EN.get(sub.type.value, sub.type.value.title())
        table_data.append([type_label, str(sub.invoice_count), format_eur_fr(sub.total_amount)])

    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("FONTNAME", (0, 0), (-1, 0), "DejaVu-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTNAME", (0, 1), (-1, -1), "DejaVu"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.black),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("ALIGN", (1, 0), (-1, 0), "CENTER"),
    ]

    table = Table(table_data, colWidths=col_widths)
    table.setStyle(TableStyle(style_cmds))
    return [Paragraph("Subtotals by type", styles["section_heading"]), table]


def _render_invoices_table(invoices: List[Invoice], styles: dict, usable_width: float) -> list:
    """'Invoices' heading + table (# | Date | Type | Recipient | Total)."""
    col_weights = [0.05, 0.12, 0.12, 0.51, 0.20]
    col_widths = [usable_width * w for w in col_weights]

    header_row = ["#", "Date", "Type", "Recipient", "Total"]
    table_data = [header_row]

    sorted_invoices = sorted(invoices, key=_invoice_sort_key)
    for idx, inv in enumerate(sorted_invoices, start=1):
        type_label = TYPE_LABEL_EN.get(inv.type.value, inv.type.value.title())
        table_data.append(
            [
                str(idx),
                inv.issue_date.strftime("%Y-%m-%d"),
                type_label,
                _xml_escape(inv.recipient_name),
                format_eur_fr(inv.total_amount),
            ]
        )

    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("FONTNAME", (0, 0), (-1, 0), "DejaVu-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTNAME", (0, 1), (-1, -1), "DejaVu"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.black),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("ALIGN", (0, 0), (0, -1), "CENTER"),
        ("ALIGN", (1, 0), (2, -1), "CENTER"),
        ("ALIGN", (3, 0), (3, -1), "LEFT"),
        ("ALIGN", (4, 0), (4, -1), "RIGHT"),
        ("ALIGN", (1, 0), (4, 0), "CENTER"),
    ]

    # Alternate row shading
    for i in range(len(sorted_invoices)):
        if i % 2 == 1:
            style_cmds.append(("BACKGROUND", (0, i + 1), (-1, i + 1), colors.HexColor("#F7F9FC")))

    table = Table(table_data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle(style_cmds))
    return [Paragraph("Invoices", styles["section_heading"]), table]


# ---------------------------------------------------------------------------
# Per-invoice page elements
# ---------------------------------------------------------------------------


def _render_invoice_page(inv: Invoice, context: InvoiceExportContext, styles: dict, usable_width: float) -> list:
    """Build all story elements for a single polished invoice page."""
    elements: list = []
    type_label = TYPE_LABEL_EN.get(inv.type.value, inv.type.value.title())

    # --- Header band: project name (left) + "INVOICE" (right) + hairline ---
    header_data = [
        [
            Paragraph(_xml_escape(context.project_name), styles["inv_header_left"]),
            Paragraph("INVOICE", styles["inv_header_right"]),
        ]
    ]
    header_table = Table(header_data, colWidths=[usable_width * 0.6, usable_width * 0.4])
    header_table.setStyle(
        TableStyle(
            [
                ("LINEBELOW", (0, 0), (-1, -1), 0.75, colors.black),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("VALIGN", (0, 0), (-1, -1), "BOTTOM"),
            ]
        )
    )
    elements.append(header_table)
    elements.append(Spacer(1, 4 * mm))

    # --- Meta block: 2-col table ---
    recipient_lines = _xml_escape(inv.recipient_name)
    if inv.recipient_address:
        recipient_lines += "<br/>" + _xml_escape(inv.recipient_address)

    meta_rows = [
        ["Invoice #", _xml_escape(inv.invoice_number)],
        ["Type", type_label],
        ["Issue date", inv.issue_date.strftime("%Y-%m-%d")],
        ["Recipient", recipient_lines],
    ]

    meta_para_rows = []
    for label, value in meta_rows:
        label_para = Paragraph(f"<b>{label}</b>", ParagraphStyle("ml", fontName="DejaVu-Bold", fontSize=9, leading=12))
        value_para = Paragraph(value, ParagraphStyle("mv", fontName="DejaVu", fontSize=9, leading=12))
        meta_para_rows.append([label_para, value_para])

    meta_table = Table(meta_para_rows, colWidths=[usable_width * 0.25, usable_width * 0.75])
    meta_table.setStyle(
        TableStyle(
            [
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    elements.append(meta_table)
    elements.append(Spacer(1, 4 * mm))

    # --- Items table: Description | Qty | Unit price | Total (zebra) ---
    items_header = ["Description", "Qty", "Unit price", "Total"]
    item_col_widths = [usable_width * 0.50, usable_width * 0.10, usable_width * 0.20, usable_width * 0.20]

    items_data = [items_header]
    for item in inv.items:
        items_data.append(
            [
                _xml_escape(item.description),
                str(item.quantity),
                format_eur_fr(item.unit_price),
                format_eur_fr(item.total),
            ]
        )

    items_style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("FONTNAME", (0, 0), (-1, 0), "DejaVu-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTNAME", (0, 1), (-1, -1), "DejaVu"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.black),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("ALIGN", (1, 0), (-1, 0), "CENTER"),
    ]

    # Zebra rows (#fafafa)
    for i in range(len(inv.items)):
        if i % 2 == 1:
            items_style_cmds.append(("BACKGROUND", (0, i + 1), (-1, i + 1), colors.HexColor("#fafafa")))

    items_table = Table(items_data, colWidths=item_col_widths)
    items_table.setStyle(TableStyle(items_style_cmds))
    elements.append(items_table)
    elements.append(Spacer(1, 2 * mm))

    # --- Grand-total band: full-width bold, light grey bg, top border ---
    grand_total_data = [["", "", "TOTAL", format_eur_fr(inv.total_amount)]]
    grand_table = Table(grand_total_data, colWidths=item_col_widths)
    grand_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#E8F0FE")),
                ("LINEABOVE", (0, 0), (-1, 0), 1.0, colors.black),
                ("FONTNAME", (0, 0), (-1, -1), "DejaVu-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("ALIGN", (2, 0), (2, 0), "RIGHT"),
                ("ALIGN", (3, 0), (3, 0), "RIGHT"),
            ]
        )
    )
    elements.append(grand_table)

    # --- Notes section (only if non-empty) ---
    if inv.notes:
        elements.append(Spacer(1, 4 * mm))
        notes_data = [
            [Paragraph("<b>Notes</b>", ParagraphStyle("nl", fontName="DejaVu-Bold", fontSize=9, leading=12))],
            [Paragraph(_xml_escape(inv.notes), ParagraphStyle("nb", fontName="DejaVu", fontSize=9, leading=12))],
        ]
        notes_table = Table(notes_data, colWidths=[usable_width])
        notes_table.setStyle(
            TableStyle(
                [
                    ("LINEABOVE", (0, 0), (-1, 0), 0.5, colors.lightgrey),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ]
            )
        )
        elements.append(notes_table)

    return elements


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_pdf(context: InvoiceExportContext, bundle: InvoiceBundle) -> bytes:
    """Generate a PDF document for invoice export and return raw bytes.

    Args:
        context: Export metadata (project, range, generated_at, user email).
        bundle:  Sorted invoices + subtotals + grand_total.

    Returns:
        Valid PDF bytes beginning with b"%PDF-".

    Page 1 — Summary (header band, meta, KPI strip, subtotals table, invoices table).
    Pages 2..N+1 — One polished invoice per page.

    Empty-range behaviour:
        If bundle.invoice_count == 0, page 1 only with "No invoices in range" paragraph.
    """
    buf = BytesIO()
    margin = 15 * mm
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=margin,
        rightMargin=margin,
        topMargin=margin,
        bottomMargin=20 * mm,  # leave room for footer
    )

    usable_width = A4[0] - 2 * margin
    styles = _make_styles()
    footer_cb = _make_footer_callback(context)

    story: list = []

    # --- Page 1: Summary ---
    story.extend(_render_summary_header(context, styles))
    story.append(Spacer(1, 4 * mm))

    if bundle.invoice_count == 0:
        from_label = context.range.from_month.strftime("%Y-%m")
        to_label = context.range.to_month.strftime("%Y-%m")
        story.append(
            Paragraph(
                f"No invoices in range {from_label} to {to_label}",
                styles["body_italic"],
            )
        )
        doc.build(story, onFirstPage=footer_cb, onLaterPages=footer_cb)
        return buf.getvalue()

    story.extend(_render_kpi_strip(bundle, context, styles))
    story.append(Spacer(1, 4 * mm))
    story.extend(_render_subtotals_table(bundle, styles, usable_width))
    story.append(Spacer(1, 4 * mm))
    story.extend(_render_invoices_table(bundle.invoices, styles, usable_width))

    # --- Pages 2..N+1: one per invoice ---
    sorted_invoices = sorted(bundle.invoices, key=_invoice_sort_key)
    for inv in sorted_invoices:
        story.append(PageBreak())
        story.extend(_render_invoice_page(inv, context, styles, usable_width))

    doc.build(story, onFirstPage=footer_cb, onLaterPages=footer_cb)
    return buf.getvalue()
