"""Invoice domain exceptions."""


class InvoiceNotFoundError(Exception):
    """Raised when an invoice cannot be found by ID."""

    pass


class InvalidInvoiceDataError(ValueError):
    """Raised when invoice data fails validation."""

    pass


class InvoiceNumberConflictError(Exception):
    """Raised when invoice number conflicts within a project."""

    pass


class AutoGeneratedInvoiceError(Exception):
    """Raised when attempting to edit or delete an auto-generated invoice."""

    def __init__(self, invoice_id: object = None) -> None:
        msg = "Auto-generated invoices cannot be modified or deleted"
        if invoice_id:
            msg = f"Invoice {invoice_id} is auto-generated and cannot be modified or deleted"
        super().__init__(msg)


class RefundExceedsSourceError(InvalidInvoiceDataError):
    """Raised when a refund would drive the source M&S invoice net below zero.

    The message includes the remaining refundable amount so the caller can
    surface a precise error to the user.
    """

    pass


class ServiceMonthNotAllowedError(InvalidInvoiceDataError):
    """Raised when service_month is set on an invoice whose type is not 'labor'."""

    pass


class AppliedAmountExceedsTargetError(InvalidInvoiceDataError):
    """Raised when an avoir return's applied amount would exceed the target invoice's total.

    The message includes the remaining applicable amount so the caller can surface a
    precise error to the user.
    """

    pass


class WorkerLinkNotAllowedError(InvalidInvoiceDataError):
    """Raised when worker_id is set on an invoice whose type is not 'labor'."""

    pass


class CashAdvanceNotAllowedError(InvalidInvoiceDataError):
    """Raised when is_cash_advance is set on an invoice whose type is not 'released_funds'."""

    pass


class WorkerNotInProjectError(InvalidInvoiceDataError):
    """Raised when worker_id does not reference a worker in the invoice's project.

    Also raised when the worker_id does not exist at all — the same error is
    used for both cases so the response never leaks whether a given worker id
    exists outside the caller's project.
    """

    pass
