"""Invoice domain exceptions."""


class InvoiceNotFoundError(Exception):
    """Raised when an invoice cannot be found by ID."""

    pass


class InvalidInvoiceDataError(ValueError):
    """Raised when invoice data fails validation."""

    pass


class InvoiceNumberConflictError(Exception):
    """Raised when invoice number conflicts within a project."""

    pass


class AutoGeneratedInvoiceError(Exception):
    """Raised when attempting to edit or delete an auto-generated invoice."""

    def __init__(self, invoice_id: object = None) -> None:
        msg = "Auto-generated invoices cannot be modified or deleted"
        if invoice_id:
            msg = f"Invoice {invoice_id} is auto-generated and cannot be modified or deleted"
        super().__init__(msg)


class RefundExceedsSourceError(InvalidInvoiceDataError):
    """Raised when a refund would drive the source M&S invoice net below zero.

    The message includes the remaining refundable amount so the caller can
    surface a precise error to the user.
    """

    pass


class ServiceMonthNotAllowedError(InvalidInvoiceDataError):
    """Raised when service_month is set on an invoice whose type is not 'labor'."""

    pass
