"""Unit tests for DeleteBillingDocumentUseCase and the released-funds expense a paid facture owns."""

from datetime import date, datetime, timezone
from decimal import Decimal
from uuid import uuid4

import pytest

from app.application.billing.delete_billing_document_usecase import DeleteBillingDocumentUseCase
from app.application.invoice.delete_invoice import DeleteInvoiceUseCase
from app.domain.billing.enums import BillingDocumentKind, BillingDocumentStatus
from app.domain.entities.invoice import Invoice, InvoiceType
from app.domain.exceptions.invoice_exceptions import AutoGeneratedInvoiceError
from app.domain.value_objects.invoice_item import InvoiceItem
from tests.unit.application.billing.conftest import make_doc


class RecordingFundsRelease:
    def __init__(self):
        self.deleted: list = []

    def create_funds_release(self, **kwargs):  # pragma: no cover - not used here
        raise AssertionError("delete must not create a release")

    def delete_funds_release(self, source_doc_id):
        self.deleted.append(source_doc_id)


class TestDeleteBillingDocumentFundsRelease:
    def test_deleting_paid_facture_removes_its_funds_release(self, doc_repo, fake_session, user_id):
        doc = make_doc(
            user_id=user_id,
            kind=BillingDocumentKind.FACTURE,
            status=BillingDocumentStatus.PAID,
            doc_number="FAC-2026-001",
            project_id=uuid4(),
        )
        doc_repo.save(doc)
        funds = RecordingFundsRelease()

        DeleteBillingDocumentUseCase(doc_repo=doc_repo, funds_release=funds).execute(doc.id, user_id, fake_session)

        assert funds.deleted == [doc.id]
        assert doc_repo.find_by_id(doc.id) is None

    def test_deleting_devis_leaves_funds_releases_alone(self, doc_repo, fake_session, user_id):
        doc = make_doc(user_id=user_id, kind=BillingDocumentKind.DEVIS)
        doc_repo.save(doc)
        funds = RecordingFundsRelease()

        DeleteBillingDocumentUseCase(doc_repo=doc_repo, funds_release=funds).execute(doc.id, user_id, fake_session)

        assert funds.deleted == []


class _InvoiceRepo:
    def __init__(self, invoice):
        self.invoice = invoice
        self.deleted = []

    def find_by_id(self, invoice_id):
        return self.invoice if self.invoice.id == invoice_id else None

    def delete(self, invoice_id):
        self.deleted.append(invoice_id)
        return True


def _release(**overrides) -> Invoice:
    now = datetime.now(timezone.utc)
    fields = dict(
        id=uuid4(),
        project_id=uuid4(),
        invoice_number="FR-2026-0001",
        type=InvoiceType.RELEASED_FUNDS,
        issue_date=date(2026, 9, 1),
        recipient_name="Client",
        created_by=uuid4(),
        created_at=now,
        updated_at=now,
        items=[InvoiceItem(description="x", quantity=Decimal("1"), unit_price=Decimal("60"))],
        is_auto_generated=True,
    )
    fields.update(overrides)
    return Invoice(**fields)


class TestOrphanedAutoRelease:
    def test_orphaned_release_can_be_deleted(self):
        orphan = _release()
        repo = _InvoiceRepo(orphan)

        DeleteInvoiceUseCase(repo).execute(orphan.id)

        assert repo.deleted == [orphan.id]

    @pytest.mark.parametrize("link", ["source_billing_document_id", "refunds_invoice_id"])
    def test_linked_release_stays_protected(self, link):
        release = _release(**{link: uuid4()})

        with pytest.raises(AutoGeneratedInvoiceError):
            DeleteInvoiceUseCase(_InvoiceRepo(release)).execute(release.id)
