"""ReportLab PDF renderer for BillingDocument entities.

Implements BillingDocumentPdfRendererPort from app.application.billing.ports.

Layout (A4 portrait, 15 mm margins):
  1. Issuer header band  — optional logo, legal_name, address, SIRET, TVA, IBAN
  2. Document title row  — "DEVIS" or "FACTURE" + document_number (right-aligned)
  3. Recipient block (left) + Meta block (right)
  4. Items table         — Description / Qty / Unit price HT / VAT % / Total HT
  5. Totals block        — Total HT, TVA per rate, Total TTC
  6. Notes section       — if present
  7. Terms section       — if present
  8. Signature block     — left placeholder + right signature text
  9. Footer              — "Generated by Folio · Page X / Y" centered

Fonts: DejaVu Sans + DejaVu Sans Bold from app/domain/labor/export/fonts/.
       Reuses the registration guard from pdf_builder — safe to import both.
Currency: format_eur_fr() from app/domain/labor/export/format.py.
Logo fetch: 3-second timeout, fail-open (logo skipped on any error).
            Skipped entirely when running under test flag FOLIO_SKIP_LOGO_FETCH=1
            or when issuer_logo_url is None/empty.
"""

from __future__ import annotations

import hashlib
import ipaddress
import logging
import os
import socket
import urllib.parse
import warnings
from io import BytesIO
from pathlib import Path
from typing import Optional
from xml.sax.saxutils import escape as _xml_escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    HRFlowable,
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.domain.billing.document import BillingDocument
from app.domain.billing.enums import BillingDocumentKind
from app.domain.labor.export.format import format_eur_fr


def _fmt_pct(d) -> str:
    """Format a Decimal percentage without scientific notation: 10 → "10", 5.5 → "5.5"."""
    s = format(d, "f")
    # Strip trailing zeros after decimal point + dangling dot.
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    return s or "0"


logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Font registration — idempotent module-level guard
# ---------------------------------------------------------------------------
# Module-level code is serialised by the Python import system, so registering
# here eliminates the lazy-flag race condition entirely.
# pdfmetrics.registerFont raises KeyError if the name is already registered;
# we catch that (and any other error) so the import never hard-crashes.

_FONTS_DIR = Path(__file__).parent.parent.parent / "domain" / "labor" / "export" / "fonts"

_FONTS_REGISTERED = False


def _register_fonts_once() -> None:
    """Register DejaVu fonts exactly once; subsequent calls are no-ops."""
    global _FONTS_REGISTERED  # noqa: PLW0603
    if _FONTS_REGISTERED:
        return
    try:
        pdfmetrics.registerFont(TTFont("DejaVu", str(_FONTS_DIR / "DejaVuSans.ttf")))
        pdfmetrics.registerFont(TTFont("DejaVu-Bold", str(_FONTS_DIR / "DejaVuSans-Bold.ttf")))
        pdfmetrics.registerFontFamily(
            "DejaVu",
            normal="DejaVu",
            bold="DejaVu-Bold",
            italic="DejaVu",
            boldItalic="DejaVu-Bold",
        )
        _FONTS_REGISTERED = True
    except Exception as err:  # noqa: BLE001
        warnings.warn(
            f"billing_pdf_renderer: DejaVu font registration failed ({err}). "
            "PDF generation will fail if fonts are unavailable.",
            stacklevel=2,
        )


_register_fonts_once()


# ---------------------------------------------------------------------------
# Stylesheet
# ---------------------------------------------------------------------------


def _styles() -> dict:
    title = ParagraphStyle("title", fontName="DejaVu-Bold", fontSize=20, leading=24)
    # Issuer-name title: cyan blue matching the source ANN ECO CONSTRUCTION header.
    issuer_title = ParagraphStyle(
        "issuer_title",
        fontName="DejaVu-Bold",
        fontSize=14,
        leading=18,
        alignment=1,
        textColor=colors.HexColor("#00A0DF"),
    )
    h2 = ParagraphStyle("h2", fontName="DejaVu-Bold", fontSize=11, leading=14, spaceAfter=2)
    h3 = ParagraphStyle("h3", fontName="DejaVu-Bold", fontSize=9, leading=12, spaceAfter=1)
    body = ParagraphStyle("body", fontName="DejaVu", fontSize=9, leading=12)
    body_small = ParagraphStyle("body_small", fontName="DejaVu", fontSize=8, leading=10)
    body_grey = ParagraphStyle("body_grey", fontName="DejaVu", fontSize=8, leading=10, textColor=colors.grey)
    right = ParagraphStyle("right", fontName="DejaVu", fontSize=9, leading=12, alignment=2)
    right_bold = ParagraphStyle("right_bold", fontName="DejaVu-Bold", fontSize=10, leading=13, alignment=2)
    footer_style = ParagraphStyle("footer", fontName="DejaVu", fontSize=8, leading=10, alignment=1)
    label = ParagraphStyle("label", fontName="DejaVu-Bold", fontSize=8, leading=10, textColor=colors.grey)
    # Items header on orange background needs black text (not grey) for contrast.
    label_white = ParagraphStyle(
        "label_white",
        fontName="DejaVu-Bold",
        fontSize=9,
        leading=11,
        textColor=colors.black,
        alignment=1,
    )
    section_title = ParagraphStyle("section_title", fontName="DejaVu-Bold", fontSize=9, leading=12, spaceAfter=2)
    return {
        "title": title,
        "issuer_title": issuer_title,
        "h2": h2,
        "h3": h3,
        "body": body,
        "body_small": body_small,
        "body_grey": body_grey,
        "right": right,
        "right_bold": right_bold,
        "footer": footer_style,
        "label": label,
        "label_white": label_white,
        "section_title": section_title,
    }


# ---------------------------------------------------------------------------
# Logo fetch — fail-open, 3 s timeout
# ---------------------------------------------------------------------------

_SKIP_LOGO_ENV = "FOLIO_SKIP_LOGO_FETCH"


def _validate_logo_url(url: str) -> None:
    """Validate that *url* is safe to fetch as a logo.

    Raises ValueError if:
    - Scheme is not http or https.
    - Resolved host IP is private, loopback, or link-local (SSRF block).

    AWS instance metadata (169.254.169.254) is covered by the link-local
    check but is also explicit to make the guard obvious in code review.
    """
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme not in ("http", "https"):
        raise ValueError(f"Logo URL scheme must be http or https, got: {parsed.scheme!r}")

    host = parsed.hostname
    if not host:
        raise ValueError("Logo URL missing host")

    try:
        resolved_ip = socket.gethostbyname(host)
        ip_obj = ipaddress.ip_address(resolved_ip)
    except (socket.gaierror, ValueError) as exc:
        raise ValueError(f"Logo URL host could not be resolved: {exc}") from exc

    # Explicit AWS metadata check (also covered by is_link_local, but kept
    # as a named guard so auditors can spot it without reasoning about CIDR).
    if resolved_ip == "169.254.169.254":
        raise ValueError("Logo URL resolves to AWS metadata endpoint — blocked")

    if ip_obj.is_private or ip_obj.is_loopback or ip_obj.is_link_local:
        raise ValueError(f"Logo URL resolves to a non-public address — blocked ({resolved_ip})")


def _fetch_logo(url: Optional[str]) -> Optional[BytesIO]:
    """Fetch an image from *url* and return its bytes in a BytesIO buffer.

    Returns None on any error (network failure, timeout, bad content-type,
    empty URL, env skip flag, SSRF validation failure). Never raises.

    Security: URL is validated by _validate_logo_url (scheme + IP checks)
    before any network I/O is performed.
    """
    if not url:
        return None
    if os.environ.get(_SKIP_LOGO_ENV, "").strip() == "1":
        return None
    try:
        _validate_logo_url(url)

        import urllib.request

        req = urllib.request.Request(url, headers={"User-Agent": "Folio-PDF/1.0"})
        with urllib.request.urlopen(req, timeout=3) as resp:  # noqa: S310
            data = resp.read()
        if not data:
            return None
        return BytesIO(data)
    except ValueError as exc:
        # Log a fingerprint hash only — never log the user-supplied URL to
        # avoid leaking SSRF probe targets in application logs (M10).
        url_hash = hashlib.sha256(url.encode()).hexdigest()[:12]
        logger.warning("billing_pdf: logo fetch rejected (url_hash=%s): %s", url_hash, exc)
        return None
    except Exception as err:  # noqa: BLE001
        url_hash = hashlib.sha256(url.encode()).hexdigest()[:12]
        logger.debug("billing_pdf: logo fetch failed (url_hash=%s): %s", url_hash, type(err).__name__)
        return None


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------


def _build_issuer_header(doc: BillingDocument, styles: dict, usable_width: float) -> list:
    """Issuer header band: optional logo left, company info right."""
    elements = []

    logo_buf = _fetch_logo(doc.issuer_logo_url)

    # Issuer legal name in cyan, bold, sz14, centered — matches source FF00A0DF.
    info_lines = [Paragraph(_xml_escape(doc.issuer_legal_name), styles["issuer_title"])]
    if doc.issuer_address:
        for line in doc.issuer_address.splitlines():
            info_lines.append(Paragraph(_xml_escape(line), styles["body_small"]))
    if doc.issuer_siret:
        info_lines.append(Paragraph(f"SIRET : {_xml_escape(doc.issuer_siret)}", styles["body_small"]))
    if doc.issuer_tva_number:
        info_lines.append(Paragraph(f"TVA : {_xml_escape(doc.issuer_tva_number)}", styles["body_small"]))
    # IBAN / BIC moved to a dedicated "Coordonnées bancaires" block at the
    # bottom of the doc, matching the source-PDF layout for a familiar visual.

    if logo_buf:
        logo_max_h = 25 * mm
        logo_max_w = 50 * mm
        try:
            logo_img = Image(logo_buf, width=logo_max_w, height=logo_max_h, kind="bound")
            logo_cell = logo_img
        except Exception:  # noqa: BLE001
            logo_cell = Paragraph("", styles["body"])
        header_data = [[logo_cell, info_lines]]
        col_widths = [logo_max_w + 4 * mm, usable_width - logo_max_w - 4 * mm]
    else:
        header_data = [["", info_lines]]
        col_widths = [0, usable_width]

    header_table = Table(header_data, colWidths=col_widths)
    header_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    elements.append(header_table)
    return elements


def _build_title_row(doc: BillingDocument, styles: dict, usable_width: float) -> list:
    """Document title band: kind label left, number right."""
    kind_label = "DEVIS" if doc.kind == BillingDocumentKind.DEVIS else "FACTURE"
    title_data = [
        [
            Paragraph(kind_label, styles["title"]),
            Paragraph(_xml_escape(doc.document_number), styles["right_bold"]),
        ]
    ]
    t = Table(title_data, colWidths=[usable_width * 0.6, usable_width * 0.4])
    t.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "BOTTOM"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    return [t]


def _build_recipient_meta(doc: BillingDocument, styles: dict, usable_width: float) -> list:
    """Two-column block: recipient left, meta (dates/terms) right."""
    # Recipient column
    recip_lines = [Paragraph(_xml_escape(doc.recipient_name), styles["h3"])]
    if doc.recipient_address:
        for line in doc.recipient_address.splitlines():
            recip_lines.append(Paragraph(_xml_escape(line), styles["body_small"]))
    if doc.recipient_email:
        recip_lines.append(Paragraph(_xml_escape(doc.recipient_email), styles["body_small"]))
    if doc.recipient_siret:
        recip_lines.append(Paragraph(f"SIRET : {_xml_escape(doc.recipient_siret)}", styles["body_small"]))

    # Meta column
    meta_lines = [Paragraph(f"Date : {doc.issue_date.strftime('%d/%m/%Y')}", styles["body_small"])]
    if doc.kind == BillingDocumentKind.DEVIS and doc.validity_until:
        meta_lines.append(
            Paragraph(
                f"Valide jusqu'au : {doc.validity_until.strftime('%d/%m/%Y')}",
                styles["body_small"],
            )
        )
    if doc.kind == BillingDocumentKind.FACTURE:
        if doc.payment_due_date:
            meta_lines.append(
                Paragraph(
                    f"Échéance : {doc.payment_due_date.strftime('%d/%m/%Y')}",
                    styles["body_small"],
                )
            )
        if doc.payment_terms:
            meta_lines.append(
                Paragraph(
                    f"Conditions : {_xml_escape(doc.payment_terms)}",
                    styles["body_small"],
                )
            )

    col_w = usable_width / 2
    data = [[recip_lines, meta_lines]]
    t = Table(data, colWidths=[col_w, col_w])
    t.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                ("ALIGN", (1, 0), (1, 0), "RIGHT"),
            ]
        )
    )
    return [t]


def _build_items_table(doc: BillingDocument, styles: dict, usable_width: float) -> list:
    """Items table mirroring the source ANN ECO CONSTRUCTION layout exactly.

    7 visible columns: Libelle / U / Qte / PU (HT) en EUR / Avancement / Montant (HT) en EUR / TVA.
    Header row uses ORANGE background (#F18728), bold, centered with thin black grid.
    A "project repeat row" (bold dark grey) is inserted right after the header.
    Section header rows (centered bold) interleave with line-item rows.
    """
    headers = [
        Paragraph("Libellé", styles["label_white"]),
        Paragraph("U", styles["label_white"]),
        Paragraph("Qté", styles["label_white"]),
        Paragraph("PU<br/>(HT) en €", styles["label_white"]),
        Paragraph("Avancement", styles["label_white"]),
        Paragraph("Montant<br/>(HT) en €", styles["label_white"]),
        Paragraph("TVA", styles["label_white"]),
    ]
    col_weights = [6.5, 0.6, 0.7, 1.0, 1.0, 1.2, 0.6]
    total_weight = sum(col_weights)
    col_widths = [usable_width * (w / total_weight) for w in col_weights]

    table_data: list = [headers]
    section_row_idxs: list = []

    project_label = doc.notes.splitlines()[0].strip() if doc.notes else doc.recipient_name
    project_row_idx = len(table_data)
    table_data.append([Paragraph(_xml_escape(project_label), styles["body"]), "", "", "", "", "", ""])

    last_category: Optional[str] = None
    for item in doc.items:
        if item.category and item.category != last_category:
            section_row_idxs.append(len(table_data))
            table_data.append([Paragraph(_xml_escape(item.category), styles["section_title"]), "", "", "", "", "", ""])
            last_category = item.category
        elif not item.category:
            last_category = None

        qty_str = (
            str(int(item.quantity))
            if item.quantity == item.quantity.to_integral_value()
            else str(item.quantity.normalize())
        )
        table_data.append(
            [
                Paragraph(_xml_escape(item.description), styles["body_small"]),
                Paragraph("", styles["body_small"]),
                Paragraph(qty_str, styles["body_small"]),
                Paragraph(format_eur_fr(item.unit_price), styles["body_small"]),
                Paragraph("100%", styles["body_small"]),
                Paragraph(format_eur_fr(item.total_ht), styles["body_small"]),
                Paragraph(f"{_fmt_pct(item.vat_rate)}%", styles["body_small"]),
            ]
        )

    style_cmds: list = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F18728")),
        ("FONTNAME", (0, 0), (-1, 0), "DejaVu-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("VALIGN", (0, 0), (-1, 0), "MIDDLE"),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
        ("FONTNAME", (0, 1), (-1, -1), "DejaVu"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("VALIGN", (0, 1), (-1, -1), "MIDDLE"),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.black),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#888888")),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("ALIGN", (0, 1), (0, -1), "LEFT"),
        ("ALIGN", (1, 1), (-1, -1), "CENTER"),
    ]
    style_cmds.extend(
        [
            ("SPAN", (0, project_row_idx), (-1, project_row_idx)),
            ("FONTNAME", (0, project_row_idx), (-1, project_row_idx), "DejaVu-Bold"),
            ("FONTSIZE", (0, project_row_idx), (-1, project_row_idx), 9),
            ("ALIGN", (0, project_row_idx), (-1, project_row_idx), "LEFT"),
            ("TEXTCOLOR", (0, project_row_idx), (-1, project_row_idx), colors.HexColor("#222222")),
        ]
    )
    for sidx in section_row_idxs:
        style_cmds.extend(
            [
                ("SPAN", (0, sidx), (-1, sidx)),
                ("FONTNAME", (0, sidx), (-1, sidx), "DejaVu-Bold"),
                ("FONTSIZE", (0, sidx), (-1, sidx), 9),
                ("ALIGN", (0, sidx), (-1, sidx), "CENTER"),
                ("TOPPADDING", (0, sidx), (-1, sidx), 4),
                ("BOTTOMPADDING", (0, sidx), (-1, sidx), 4),
            ]
        )

    t = Table(table_data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle(style_cmds))
    return [t]


def _build_totals_block(doc: BillingDocument, styles: dict, usable_width: float) -> list:
    """Right-aligned totals block: HT, TVA per rate, TTC."""
    col_label_w = usable_width * 0.7
    col_value_w = usable_width * 0.3

    rows = []

    # Total HT
    rows.append(
        [
            Paragraph("Total HT", styles["body_small"]),
            Paragraph(format_eur_fr(doc.total_ht), styles["body_small"]),
        ]
    )

    # VAT per rate (sorted descending by rate)
    for rate, base_ht, tva_amt in doc.vat_breakdown:
        label = f"TVA {_fmt_pct(rate)} %"
        rows.append(
            [
                Paragraph(label, styles["body_small"]),
                Paragraph(format_eur_fr(tva_amt), styles["body_small"]),
            ]
        )

    # Separator then TTC
    totals_table = Table(rows, colWidths=[col_label_w, col_value_w])
    totals_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "DejaVu"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("ALIGN", (0, 0), (0, -1), "RIGHT"),
                ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                ("LINEBELOW", (0, -1), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
            ]
        )
    )

    # TTC row — bold, larger
    ttc_data = [
        [
            Paragraph("Total TTC", styles["right_bold"]),
            Paragraph(format_eur_fr(doc.total_ttc), styles["right_bold"]),
        ]
    ]
    ttc_table = Table(ttc_data, colWidths=[col_label_w, col_value_w])
    ttc_table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "DejaVu-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EEF2FA")),
            ]
        )
    )
    return [totals_table, ttc_table]


def _build_text_section(title: str, content: str, styles: dict) -> list:
    """Generic titled text block (notes / terms)."""
    elements: list = [
        HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CCCCCC")),
        Spacer(1, 3 * mm),
        Paragraph(title, styles["section_title"]),
    ]
    for line in content.splitlines():
        elements.append(Paragraph(_xml_escape(line) or " ", styles["body"]))
    return elements


def _build_bank_coords_block(doc: BillingDocument, styles: dict, usable_width: float) -> list:
    """Render a 'Coordonnées bancaires' block when IBAN/BIC are present.

    Mirrors the source-PDF layout: a labelled, lightly-bordered band at the
    bottom of the doc with IBAN + BIC. Returns [] if no bank info is set.
    """
    if not doc.issuer_iban and not doc.issuer_bic:
        return []
    rows: list = [[Paragraph("COORDONNÉES BANCAIRES", styles["section_title"]), ""]]
    if doc.issuer_iban:
        rows.append(
            [
                Paragraph("IBAN", styles["label"]),
                Paragraph(_xml_escape(doc.issuer_iban), styles["body_small"]),
            ]
        )
    if doc.issuer_bic:
        rows.append(
            [
                Paragraph("BIC", styles["label"]),
                Paragraph(_xml_escape(doc.issuer_bic), styles["body_small"]),
            ]
        )
    label_w = 25 * mm
    t = Table(rows, colWidths=[label_w, usable_width - label_w])
    t.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "DejaVu"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("SPAN", (0, 0), (-1, 0)),  # title row spans both columns
                # Orange band (FFF18728) matching the source COORDONNÉES BANCAIRES header.
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F18728")),
                ("ALIGN", (0, 0), (-1, 0), "CENTER"),
                ("FONTNAME", (0, 0), (-1, 0), "DejaVu-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
            ]
        )
    )
    return [t]


def _build_legal_footer_note(styles: dict) -> list:
    """Standard French construction-invoice late-payment legal note."""
    text = (
        "Indemnité forfaitaire de retard de paiement : 40 € "
        "(conformément à l'article 121-II de la loi n° 2012-387 du 22 Mars 2012 "
        "et au décret n° 2012-1115 du 2 Oct. 2012)."
    )
    return [Paragraph(_xml_escape(text), styles["body_grey"])]


def _build_greeting_block(doc: BillingDocument, styles: dict) -> list:
    """Render the standard French opening: 'Madame, Monsieur,' + 2 short paragraphs.

    Mirrors the source layout (rows 19-21 in the xlsx).
    """
    intro_subject = "facture" if doc.kind == BillingDocumentKind.FACTURE else "devis"
    return [
        Paragraph("Madame, Monsieur,", styles["body"]),
        Spacer(1, 1 * mm),
        Paragraph(
            f"Veuillez trouver ci-après le {intro_subject} relatif à la mission citée en objet.",
            styles["body"],
        ),
        Paragraph(
            "Je reste à votre disposition pour toute précision ou complément d'information.",
            styles["body"],
        ),
    ]


def _build_closing_greeting(styles: dict) -> list:
    """Standard closing line above the bank coords (mirrors B71 in source xlsx)."""
    return [
        Paragraph(
            "Veuillez agréer, Madame, Monsieur, l'expression de nos salutations distinguées.",
            styles["body"],
        )
    ]


def _build_signature_block(doc: BillingDocument, styles: dict, usable_width: float) -> list:
    """Two-column signature band: client left, issuer right."""
    left_text = "Signature du client :"
    right_text = doc.signature_block_text or "Signature :"

    sig_data = [
        [
            Paragraph(left_text, styles["body_small"]),
            Paragraph(_xml_escape(right_text), styles["body_small"]),
        ],
        [
            Paragraph(" ", styles["body"]),  # space for signature
            Paragraph(" ", styles["body"]),
        ],
    ]
    t = Table(sig_data, colWidths=[usable_width / 2, usable_width / 2])
    t.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "DejaVu"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 20),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("BOX", (0, 0), (0, -1), 0.5, colors.HexColor("#CCCCCC")),
                ("BOX", (1, 0), (1, -1), 0.5, colors.HexColor("#CCCCCC")),
            ]
        )
    )
    return [t]


# ---------------------------------------------------------------------------
# Footer callback
# ---------------------------------------------------------------------------


def _make_footer_callback():
    """Return a canvas callback that draws 'Generated by Folio · Page X / Y'."""

    def _on_page(canvas, doc) -> None:  # type: ignore[no-untyped-def]
        canvas.saveState()
        canvas.setFont("DejaVu", 8)
        text = f"Generated by Folio · Page {doc.page}"
        page_width = A4[0]
        canvas.drawCentredString(page_width / 2, 8 * mm, text)
        canvas.restoreState()

    return _on_page


# ---------------------------------------------------------------------------
# Public renderer
# ---------------------------------------------------------------------------


class ReportLabBillingDocumentPdfRenderer:
    """Implements BillingDocumentPdfRendererPort via ReportLab Platypus.

    Instantiate once and call render() for each document.
    Font registration is done at module import time and is idempotent.
    """

    def render(self, doc: BillingDocument) -> bytes:
        """Render *doc* to a valid A4 PDF byte string.

        Returns raw PDF bytes starting with b"%PDF-".
        Never raises due to logo fetch errors (fail-open).
        Raises if ReportLab cannot build the document (missing fonts, etc.).
        """
        _register_fonts_once()  # safe no-op if already registered

        buf = BytesIO()
        margin = 15 * mm
        pdf_doc = SimpleDocTemplate(
            buf,
            pagesize=A4,
            leftMargin=margin,
            rightMargin=margin,
            topMargin=margin,
            bottomMargin=22 * mm,  # room for footer
        )
        usable_width = A4[0] - 2 * margin
        s = _styles()
        footer_cb = _make_footer_callback()

        story: list = []

        # 1. Issuer header
        story.extend(_build_issuer_header(doc, s, usable_width))
        story.append(Spacer(1, 5 * mm))

        # 2. Title row
        story.extend(_build_title_row(doc, s, usable_width))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#3B5BDB")))
        story.append(Spacer(1, 5 * mm))

        # 3. Recipient + meta
        story.extend(_build_recipient_meta(doc, s, usable_width))
        story.append(Spacer(1, 5 * mm))

        # 3b. Greeting block — "Madame, Monsieur," + 2 short paragraphs
        story.extend(_build_greeting_block(doc, s))
        story.append(Spacer(1, 4 * mm))

        # 4. Items table
        if doc.items:
            story.extend(_build_items_table(doc, s, usable_width))
        else:
            story.append(Paragraph("Aucun article.", s["body_small"]))
        story.append(Spacer(1, 4 * mm))

        # 5. Totals block
        story.extend(_build_totals_block(doc, s, usable_width))
        story.append(Spacer(1, 6 * mm))

        # 6. Notes (only if explicitly used as extra notes, not project description)
        # Skip rendering — project description is now displayed in the items table
        # project repeat row, so notes-as-project-description would duplicate.

        # 7. Terms / conditions générales
        if doc.terms and doc.terms.strip():
            story.extend(_build_text_section("Conditions générales", doc.terms, s))
            story.append(Spacer(1, 4 * mm))

        # 8. Closing greeting (mirrors B71 in source xlsx)
        story.extend(_build_closing_greeting(s))
        story.append(Spacer(1, 4 * mm))

        # 9. Coordonnées bancaires (if IBAN/BIC present) — orange band
        bank_block = _build_bank_coords_block(doc, s, usable_width)
        if bank_block:
            story.extend(bank_block)

        # 10. Late-payment legal note (factures only — devis don't trigger this)
        if doc.kind == BillingDocumentKind.FACTURE:
            story.append(Spacer(1, 3 * mm))
            story.extend(_build_legal_footer_note(s))

        pdf_doc.build(story, onFirstPage=footer_cb, onLaterPages=footer_cb)
        return buf.getvalue()
