"""API key generation — plaintext, non-secret display prefix, and lookup hash.

We hash with SHA-256 (via ``hash_token``) instead of bcrypt/argon2, and this
is deliberate rather than an oversight. A slow, salted KDF exists to make a
single guess expensive, because humans reuse short, low-entropy, guessable
passwords and an attacker can try candidates offline. An API key is not that:
it is a 256-bit value drawn from ``secrets.token_urlsafe``, generated by us,
never chosen by a human, and never reused across sites. There is no
"guess towards" — the input space is the full token, so no realistic amount
of compute makes brute-forcing it viable, salted or not. What verification
actually needs is a single indexed equality lookup on a value the server
cannot itself salt-guess ahead of time, which is exactly what a plain
SHA-256 digest gives us. A slow KDF would only add latency to every single
authenticated request (this hash runs on every API-key-bearing call) without
closing any real gap, so SHA-256 is the correct trade-off here, not a
shortcut.
"""

from __future__ import annotations

import secrets

from app.domain.value_objects.invite_token import hash_token

# Non-secret marker prefixing every plaintext key. Lets the authentication
# seam (app/api/_helpers/api_key_request_auth.py) recognize an API-key
# credential before ever touching the database, and lets a human recognize a
# leaked key in logs or a screenshot.
API_KEY_PREFIX = "folio_sk_"

# Length of the stored, listing-safe prefix (includes API_KEY_PREFIX itself).
_DISPLAY_PREFIX_LEN = 16


def generate_api_key() -> tuple[str, str, str]:
    """Generate a new API key.

    Returns:
        (plaintext, prefix, token_hash) — ``plaintext`` is handed back to the
        caller exactly once and is never persisted; ``prefix`` (the first 16
        characters of the plaintext) is stored and shown in listings so a
        user can tell their keys apart without re-exposing the secret;
        ``token_hash`` is the sha256 hex digest used for verification lookup.
    """
    plaintext = API_KEY_PREFIX + secrets.token_urlsafe(32)
    prefix = plaintext[:_DISPLAY_PREFIX_LEN]
    token_hash = hash_token(plaintext)
    return plaintext, prefix, token_hash
